"""Tests that every plugin ships the hook scripts its hooks.json dispatches to.

`hooks.json` is now generated by `scripts/stamp.py` from each hook script's own
`WORKSHOP_HOOK` declaration -- dropping a script into `hooks/scripts/` *is* the
wiring (see `scripts/stamp.py`'s module docstring). That does not retire the
property this file guards: a generator bug that emits a `run-hook.sh` command
for a script no longer present in `hooks/scripts/` produces a hook that fails
silently at runtime on a user's machine, and PreToolUse hooks fail closed, so
a missing `protect-files.py`-style script blocks every Write and Edit with no
clear error.

This walks each plugin's REAL, already-stamped `hooks.json` -- not a rebuild
of one -- and checks its dispatch against what actually shipped in that same
plugin's `hooks/scripts/`.
"""

import json
import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]

# run-hook.sh dispatches a bare `<script>.py`, or a runner switch ahead of it
# (currently just `--uv`, for a PEP-723 hook run under `uv run`); either form
# names the script last.
_DISPATCHED_SCRIPT_RE = re.compile(r"run-hook\.sh\s+(?:--\w+\s+)*([\w.-]+\.py)")


def _plugin_hooks_json_paths() -> list[Path]:
    """Every plugin's hooks.json that actually exists in the repo.

    Not every plugin ships hooks -- a plugin with no hook scripts has no
    WORKSHOP_HOOK declarations, so `scripts/stamp.py` never writes it one
    (`plugin.hooks_json is None`). Those plugins are simply absent from this
    list rather than represented by an empty file.
    """
    return sorted((REPO_ROOT / "plugins").glob("*/hooks/hooks.json"))


def _missing_scripts(hooks_json_path: Path) -> set[str]:
    """Scripts a hooks.json dispatches to that are absent from hooks/scripts/."""
    hooks_json = json.loads(hooks_json_path.read_text())
    dispatched = set(_DISPATCHED_SCRIPT_RE.findall(json.dumps(hooks_json)))
    shipped = {p.name for p in (hooks_json_path.parent / "scripts").glob("*.py")}
    return dispatched - shipped


@pytest.mark.parametrize(
    "hooks_json_path",
    _plugin_hooks_json_paths(),
    ids=[p.parent.parent.name for p in _plugin_hooks_json_paths()],
)
def test_every_dispatched_script_is_shipped(hooks_json_path: Path) -> None:
    """A plugin's hooks.json never names a script missing from hooks/scripts/."""
    missing = _missing_scripts(hooks_json_path)
    plugin = hooks_json_path.parent.parent.name
    assert not missing, (
        f"{plugin}/hooks/hooks.json dispatches to {sorted(missing)}, which is "
        f"not in {plugin}/hooks/scripts/. Every matching tool call would fail "
        f"with a FileNotFoundError from run-hook.sh -- and PreToolUse hooks "
        f"fail closed, so a missing script there blocks every Write and Edit."
    )


def test_check_has_teeth_against_a_hooks_json_naming_a_missing_script(
    tmp_path: Path, make_plugin
) -> None:
    """A hooks.json naming a never-shipped script must be flagged as missing.

    Without this, the property above could pass for the wrong reason -- e.g.
    the regex silently matching nothing -- and nobody would notice. Build a
    plugin whose hooks/scripts/ only has the fixture's `demo-hook.py`, but
    hand-write a hooks.json that dispatches to `ghost-script.py`, which was
    never dropped in. The same detection logic the real test above uses must
    flag it.
    """
    plugin_dir = make_plugin(tmp_path, "broken-hooks", hooks=True)
    hooks_json_path = plugin_dir / "hooks" / "hooks.json"
    hooks_json_path.write_text(
        json.dumps(
            {
                "hooks": {
                    "Stop": [
                        {
                            "hooks": [
                                {
                                    "type": "command",
                                    "command": (
                                        'bash "${CLAUDE_PLUGIN_ROOT}"/hooks/'
                                        "run-hook.sh ghost-script.py"
                                    ),
                                }
                            ]
                        }
                    ]
                }
            },
            indent=2,
        )
    )

    assert _missing_scripts(hooks_json_path) == {"ghost-script.py"}
