"""Generate the repo's living reference documentation from component metadata.

Single source of truth for the docs is the components themselves: SKILL.md and
AGENT.md frontmatter, hook module docstrings, hook wiring in the settings JSON,
and preset ``manifest.json`` files. This module parses that metadata once into a
model, then renders it into two shapes:

* **Fully generated catalog pages** under ``docs/reference/`` — one per component
  type (``skills.md``, ``hooks.md``, ``agents.md``, ``presets.md``,
  ``methodology.md``). These carry a "do not edit" banner and are rewritten
  whole on every run.
* **Marker-injected regions** inside hand-written prose — the root ``README.md``
  and ``docs/reference/build-and-wiring.md``. Only the content between
  ``<!-- BEGIN GENERATED: <id> -->`` / ``<!-- END GENERATED: <id> -->`` markers
  is rewritten; the surrounding prose is human-owned.

Rendering is deterministic (everything sorted), so re-running is a no-op when the
tree is fresh. ``build_docs --check`` regenerates in memory and exits non-zero if
any committed output is stale — this is the drift gate the ``make test`` target
and CI enforce.

The renderers are also imported by ``build_preset._generate_readme`` so each
built plugin's dist README shares the same per-component reference shape.
"""

from __future__ import annotations

import ast
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

from scripts.smoke_test import _parse_frontmatter

# Claude Code hook events. Used to tell a hook docstring's *claimed* event
# (e.g. "Stop hook: ...") apart from a descriptive prefix (e.g. "Pre-edit
# hook: ..."). Only a claimed event that is a real event name is cross-checked
# against the wiring; a descriptive prefix is left alone.
KNOWN_EVENTS = frozenset(
    {
        "PreToolUse",
        "PostToolUse",
        "UserPromptSubmit",
        "Notification",
        "Stop",
        "SubagentStart",
        "SubagentStop",
        "SessionStart",
        "SessionEnd",
        "PreCompact",
        "ConfigChange",
    }
)

# The non-hook, non-methodology doc under core/docs that is project-specific and
# never ships in a preset; excluded from the methodology catalog too.
_PROJECT_DOC = "project.md"

# run-hook.sh <script>.py  OR  hooks/scripts/<script>.py — the two command
# shapes used across base and preset settings.
_HOOK_SCRIPT_RE = re.compile(r"(?:run-hook\.sh\s+|hooks/scripts/)([\w.-]+\.py)")

# A GENERATED marker pair, matched by id so the same id can be filled anywhere.
# The body is captured lazily and may be empty, so the initial adjacent
# BEGIN/END state (no content yet) still matches and gets filled.
_MARKER_RE = re.compile(
    r"<!-- BEGIN GENERATED: (?P<id>[A-Za-z0-9_-]+) -->\n"
    r"(?P<body>.*?)"
    r"<!-- END GENERATED: (?P=id) -->",
    re.DOTALL,
)

_DO_NOT_EDIT = (
    "<!-- Generated by scripts/build_docs.py — do not edit by hand.\n"
    "     Run `make docs` after changing a skill, hook, agent, or preset. -->"
)


class DocsError(Exception):
    """Raised when documentation generation hits malformed or inconsistent input."""


@dataclass(frozen=True)
class SkillDoc:
    """A skill's documented surface, parsed from its SKILL.md frontmatter."""

    name: str
    description: str
    source: str  # "core" or a preset name (the preset that owns an override)
    presets: tuple[str, ...] = ()  # presets that ship this skill
    overrides_core: bool = False


@dataclass(frozen=True)
class AgentDoc:
    """An agent's documented surface, parsed from its AGENT.md frontmatter."""

    name: str
    description: str
    role: str
    skills_add: tuple[str, ...]
    source: str
    presets: tuple[str, ...] = ()
    overrides_core: bool = False


@dataclass(frozen=True)
class HookDoc:
    """A hook script's documented surface: docstring summary + wired events."""

    name: str
    summary: str
    source: str  # "core" or a preset name
    events: tuple[str, ...] = ()
    matchers: tuple[str, ...] = ()
    presets: tuple[str, ...] = ()


@dataclass(frozen=True)
class MethodologyDoc:
    """A methodology doc under core/docs (title + first paragraph)."""

    filename: str
    title: str
    summary: str


@dataclass(frozen=True)
class ScriptDoc:
    """A build/tooling script under scripts/ (module docstring first line)."""

    filename: str
    summary: str


@dataclass(frozen=True)
class PresetDoc:
    """A preset's documented surface, derived from its manifest + settings."""

    name: str
    description: str
    version: str
    is_persona: bool
    skills: tuple[str, ...]
    agents: tuple[str, ...]
    hooks: tuple[str, ...]
    conventions: tuple[str, ...]


@dataclass
class DocsModel:
    """The full parsed model rendered into every doc page."""

    skills: list[SkillDoc] = field(default_factory=list)
    agents: list[AgentDoc] = field(default_factory=list)
    hooks: list[HookDoc] = field(default_factory=list)
    methodology: list[MethodologyDoc] = field(default_factory=list)
    scripts: list[ScriptDoc] = field(default_factory=list)
    presets: list[PresetDoc] = field(default_factory=list)


# --------------------------------------------------------------------------- #
# Parsing helpers
# --------------------------------------------------------------------------- #


# Abbreviations whose internal period must not be treated as a sentence end.
_ABBREVIATIONS = frozenset(
    {"e.g", "i.e", "etc", "vs", "cf", "approx", "al", "no", "fig", "eq", "ca"}
)


def _first_sentence(text: str) -> str:
    """Return the first sentence of a description for summary tables.

    A period ends the sentence only when the word before it isn't a known
    abbreviation ("e.g.", "etc.") or a bare number/letter ("Python 3." /
    "point A."), so summaries aren't truncated mid-clause.
    """
    text = " ".join(text.split())
    for match in re.finditer(r"[.!?](\s|$)", text):
        end = match.start()
        token = text[:end].rsplit(" ", 1)[-1].rstrip(".").lower()
        if token in _ABBREVIATIONS:
            continue
        if len(token) <= 1 and token.isalnum():
            continue
        return text[: end + 1].strip()
    return text


def _escape_cell(text: str) -> str:
    """Escape a value for a Markdown table cell (pipes, newlines)."""
    return " ".join(text.split()).replace("|", "\\|")


def _load_frontmatter(md_path: Path, label: str) -> dict:
    """Parse frontmatter or raise a DocsError naming the offending file."""
    frontmatter = _parse_frontmatter(md_path.read_text(encoding="utf-8"))
    if frontmatter is None:
        raise DocsError(f"{label} '{md_path}' has no valid frontmatter")
    return frontmatter


def _require_str(frontmatter: dict, field_name: str, label: str) -> str:
    """Return a required string field, or raise DocsError naming the file.

    Guards against the frontmatter parser returning a non-string (e.g. a dict
    when a plain multiline value's continuation line contains a colon) — that
    must fail loudly rather than ship a ``{...}`` repr in the docs.
    """
    value = frontmatter.get(field_name)
    if not isinstance(value, str) or not value.strip():
        raise DocsError(f"{label} missing or non-string field '{field_name}'")
    return value.strip()


def _parse_skill(skill_dir: Path, source: str) -> SkillDoc:
    """Parse one skill directory into a SkillDoc, failing fast on bad metadata."""
    skill_md = skill_dir / "SKILL.md"
    if not skill_md.exists():
        raise DocsError(f"Skill '{skill_dir.name}' has no SKILL.md at {skill_md}")
    frontmatter = _load_frontmatter(skill_md, "Skill")
    label = f"Skill '{skill_dir.name}/SKILL.md'"
    return SkillDoc(
        name=_require_str(frontmatter, "name", label),
        description=_require_str(frontmatter, "description", label),
        source=source,
    )


def _parse_agent(agent_dir: Path, source: str) -> AgentDoc:
    """Parse one agent directory into an AgentDoc, failing fast on bad metadata."""
    agent_md = agent_dir / "AGENT.md"
    if not agent_md.exists():
        raise DocsError(f"Agent '{agent_dir.name}' has no AGENT.md at {agent_md}")
    frontmatter = _load_frontmatter(agent_md, "Agent")
    label = f"Agent '{agent_dir.name}/AGENT.md'"
    skills_config = frontmatter.get("skills", {})
    skills_add: tuple[str, ...] = ()
    if isinstance(skills_config, dict):
        add = skills_config.get("add", [])
        if isinstance(add, list):
            skills_add = tuple(str(s) for s in add)
    return AgentDoc(
        name=_require_str(frontmatter, "name", label),
        description=_require_str(frontmatter, "description", label),
        role=_require_str(frontmatter, "role", label),
        skills_add=skills_add,
        source=source,
    )


def _parse_hook_summary(hook_path: Path) -> str:
    """Return the first line of a hook module's docstring, failing fast if absent."""
    try:
        tree = ast.parse(hook_path.read_text(encoding="utf-8"))
    except SyntaxError as exc:
        raise DocsError(
            f"Hook '{hook_path.name}' is not parseable Python: {exc}"
        ) from exc
    docstring = ast.get_docstring(tree)
    if not docstring:
        raise DocsError(
            f"Hook '{hook_path.name}' has no module docstring; the first line "
            "documents what the hook does and is required for the reference."
        )
    return docstring.strip().split("\n", 1)[0].strip()


def _claimed_event(summary: str) -> str | None:
    """Extract a leading '<Token> hook:' token from a hook summary, if present."""
    match = re.match(r"([A-Za-z][\w-]*)\s+hook:", summary)
    return match.group(1) if match else None


def _script_from_command(command: str) -> str | None:
    """Extract the hook script filename from a settings hook command string."""
    match = _HOOK_SCRIPT_RE.search(command)
    return match.group(1) if match else None


def _walk_hook_wiring(settings: dict) -> dict[str, dict[str, set[str]]]:
    """Map hook script name -> {"events": {...}, "matchers": {...}} from settings."""
    wiring: dict[str, dict[str, set[str]]] = {}
    for event, entries in settings.get("hooks", {}).items():
        if not isinstance(entries, list):
            continue
        for entry in entries:
            matcher = entry.get("matcher", "")
            for hook in entry.get("hooks", []):
                script = _script_from_command(hook.get("command", ""))
                if not script:
                    continue
                record = wiring.setdefault(script, {"events": set(), "matchers": set()})
                record["events"].add(event)
                if matcher:
                    record["matchers"].add(matcher)
    return wiring


def _merged_settings_for(preset_dir: Path, base_settings_path: Path) -> dict:
    """Return the settings a preset actually ships (base-merged or preset-only)."""
    # Local import avoids a circular import: build_preset imports this module's
    # renderers for its dist README.
    from scripts.build_preset import _merge_settings

    manifest = _read_json(preset_dir / "manifest.json")
    preset_settings_path = preset_dir / "settings-preset.json"
    if manifest.get("base_settings", True):
        return _merge_settings(base_settings_path, preset_settings_path)
    if preset_settings_path.exists():
        return _read_json(preset_settings_path)
    return {}


def _read_json(path: Path) -> dict:
    import json

    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise DocsError(f"Expected JSON not found: {path}") from exc
    except ValueError as exc:
        raise DocsError(f"Invalid JSON in {path}: {exc}") from exc


def _parse_methodology(doc_path: Path) -> MethodologyDoc:
    """Parse a methodology doc's title (first heading) and first paragraph."""
    lines = doc_path.read_text(encoding="utf-8").split("\n")
    title = doc_path.stem
    summary = ""
    body: list[str] = []
    for line in lines:
        if line.startswith("#") and title == doc_path.stem:
            title = line.lstrip("#").strip()
            continue
        if line.strip() and not line.startswith("#"):
            body.append(line.strip())
        elif body:
            break
    if body:
        summary = " ".join(body)
    return MethodologyDoc(filename=doc_path.name, title=title, summary=summary)


# --------------------------------------------------------------------------- #
# Model assembly
# --------------------------------------------------------------------------- #


def _preset_dirs(root: Path) -> list[Path]:
    return sorted(
        d
        for d in (root / "presets").iterdir()
        if d.is_dir() and (d / "manifest.json").exists()
    )


_BUILD_ARTIFACT_DIRS = frozenset({"__pycache__", ".pytest_cache", ".ruff_cache"})


def _is_build_artifact(path: Path, base: Path) -> bool:
    relative = path.relative_to(base)
    return bool(_BUILD_ARTIFACT_DIRS.intersection(relative.parts)) or path.suffix == ".pyc"


def is_leftover_artifact_dir(component_dir: Path) -> bool:
    """True when a directory's whole content is build artifacts git left behind.

    Switching off a branch that added a component removes its tracked files but
    keeps ignored ones — git will not delete ignored content. The empty shell
    that remains is not a malformed component, it is debris, and reporting it as
    a component names something that does not exist on the current branch.

    An *empty* directory is deliberately not treated as debris: git never
    creates one on checkout, so it can only be hand-made, and that is a real
    mistake worth failing on.
    """
    files = [p for p in component_dir.rglob("*") if p.is_file()]
    return bool(files) and all(_is_build_artifact(p, component_dir) for p in files)


def _component_dirs(parent: Path) -> list[Path]:
    """Component directories under `parent`, skipping build-artifact debris."""
    if not parent.exists():
        return []
    return sorted(
        d for d in parent.iterdir() if d.is_dir() and not is_leftover_artifact_dir(d)
    )


def _core_skill_names(root: Path) -> list[str]:
    return [d.name for d in _component_dirs(root / "core" / "skills")]


def _core_agent_names(root: Path) -> list[str]:
    return [d.name for d in _component_dirs(root / "core" / "agents")]


def _shipped_skills(manifest: dict, core_skills: list[str]) -> list[str]:
    setting = manifest.get("core", {}).get("skills", "all")
    shipped = list(core_skills) if setting == "all" else list(setting)
    shipped += [s for s in manifest.get("preset_skills", []) if s not in shipped]
    excluded = {
        e.split("/", 1)[1]
        for e in manifest.get("exclude", [])
        if e.startswith("skills/")
    }
    return sorted(s for s in shipped if s not in excluded)


def _shipped_agents(manifest: dict, core_agents: list[str]) -> list[str]:
    setting = manifest.get("core", {}).get("agents", "all")
    shipped = list(core_agents) if setting == "all" else list(setting)
    shipped += [a for a in manifest.get("preset_agents", []) if a not in shipped]
    excluded = {
        e.split("/", 1)[1]
        for e in manifest.get("exclude", [])
        if e.startswith("agents/")
    }
    return sorted(a for a in shipped if a not in excluded)


def _shipped_hooks(manifest: dict) -> list[str]:
    hooks = list(manifest.get("core", {}).get("hooks", []))
    hooks += [h for h in manifest.get("preset_hooks", []) if h not in hooks]
    # Hooks are excluded as `hooks/scripts/<name>` — the form build_preset
    # validates against. Without this filter the generated tables and the dist
    # README claim a preset ships a hook the build never copies.
    excluded = {
        e.split("/")[-1]
        for e in manifest.get("exclude", [])
        if e.startswith("hooks/scripts/")
    }
    return sorted(h for h in hooks if h not in excluded)


def build_model(root: Path) -> DocsModel:
    """Parse core + presets into the full documentation model."""
    model = DocsModel()
    core_skills = _core_skill_names(root)
    core_agents = _core_agent_names(root)
    base_settings_path = root / "core" / "settings-base.json"
    preset_dirs = _preset_dirs(root)

    # Per-preset manifests + inventories, and the inverse skill/agent -> presets map.
    manifests: dict[str, dict] = {}
    presets_with_skill: dict[str, set[str]] = {}
    presets_with_agent: dict[str, set[str]] = {}
    presets_with_hook: dict[str, set[str]] = {}
    for preset_dir in preset_dirs:
        manifest = _read_json(preset_dir / "manifest.json")
        manifests[preset_dir.name] = manifest
        for skill in _shipped_skills(manifest, core_skills):
            presets_with_skill.setdefault(skill, set()).add(preset_dir.name)
        for agent in _shipped_agents(manifest, core_agents):
            presets_with_agent.setdefault(agent, set()).add(preset_dir.name)
        for hook in _shipped_hooks(manifest):
            presets_with_hook.setdefault(hook, set()).add(preset_dir.name)

    # Skills: core, then preset-owned skills (overrides + preset-only).
    seen_skill_names: set[str] = set()
    for name in core_skills:
        skill = _parse_skill(root / "core" / "skills" / name, "core")
        model.skills.append(
            SkillDoc(
                name=skill.name,
                description=skill.description,
                source="core",
                presets=tuple(sorted(presets_with_skill.get(name, set()))),
            )
        )
        seen_skill_names.add(name)
    for preset_dir in preset_dirs:
        for skill_dir in _component_dirs(preset_dir / "skills"):
            skill = _parse_skill(skill_dir, preset_dir.name)
            model.skills.append(
                SkillDoc(
                    name=skill.name,
                    description=skill.description,
                    source=preset_dir.name,
                    presets=tuple(
                        sorted(presets_with_skill.get(skill_dir.name, set()))
                    ),
                    overrides_core=skill_dir.name in seen_skill_names,
                )
            )
    model.skills.sort(key=lambda s: (s.source != "core", s.name))

    # Agents: core, then preset-owned.
    seen_agent_names: set[str] = set()
    for name in core_agents:
        agent = _parse_agent(root / "core" / "agents" / name, "core")
        model.agents.append(
            AgentDoc(
                name=agent.name,
                description=agent.description,
                role=agent.role,
                skills_add=agent.skills_add,
                source="core",
                presets=tuple(sorted(presets_with_agent.get(name, set()))),
            )
        )
        seen_agent_names.add(name)
    for preset_dir in preset_dirs:
        for agent_dir in _component_dirs(preset_dir / "agents"):
            agent = _parse_agent(agent_dir, preset_dir.name)
            model.agents.append(
                AgentDoc(
                    name=agent.name,
                    description=agent.description,
                    role=agent.role,
                    skills_add=agent.skills_add,
                    source=preset_dir.name,
                    presets=tuple(
                        sorted(presets_with_agent.get(agent_dir.name, set()))
                    ),
                    overrides_core=agent_dir.name in seen_agent_names,
                )
            )
    model.agents.sort(key=lambda a: (a.source != "core", a.name))

    # Hook wiring aggregated across every preset's shipped settings.
    wiring: dict[str, dict[str, set[str]]] = {}
    for preset_dir in preset_dirs:
        settings = _merged_settings_for(preset_dir, base_settings_path)
        for script, record in _walk_hook_wiring(settings).items():
            agg = wiring.setdefault(script, {"events": set(), "matchers": set()})
            agg["events"] |= record["events"]
            agg["matchers"] |= record["matchers"]

    # Hooks: core hook scripts, then any preset-only hook scripts (e.g. post-edit-lint).
    hook_paths: dict[str, tuple[Path, str]] = {}
    core_hooks_dir = root / "core" / "hooks"
    if core_hooks_dir.exists():
        for hook_path in sorted(core_hooks_dir.glob("*.py")):
            hook_paths[hook_path.name] = (hook_path, "core")
    for preset_dir in preset_dirs:
        hooks_dir = preset_dir / "hooks"
        if not hooks_dir.exists():
            continue
        for hook_path in sorted(hooks_dir.glob("*.py")):
            hook_paths.setdefault(hook_path.name, (hook_path, preset_dir.name))

    for name, (hook_path, source) in sorted(hook_paths.items()):
        summary = _parse_hook_summary(hook_path)
        record = wiring.get(name, {"events": set(), "matchers": set()})
        events = tuple(sorted(record["events"]))
        _cross_validate_hook(name, summary, events)
        model.hooks.append(
            HookDoc(
                name=name,
                summary=summary,
                source=source,
                events=events,
                matchers=tuple(sorted(record["matchers"])),
                presets=tuple(sorted(presets_with_hook.get(name, set()))),
            )
        )

    # Methodology docs under core/docs (project.md excluded).
    docs_dir = root / "core" / "docs"
    if docs_dir.exists():
        for doc_path in sorted(docs_dir.glob("*.md")):
            if doc_path.name == _PROJECT_DOC:
                continue
            model.methodology.append(_parse_methodology(doc_path))

    # Build/tooling scripts (module docstring first line).
    scripts_dir = root / "scripts"
    if scripts_dir.exists():
        for script_path in sorted(scripts_dir.glob("*.py")):
            if script_path.name in ("__init__.py", "__main__.py"):
                continue
            summary = _script_summary(script_path)
            if summary:
                model.scripts.append(
                    ScriptDoc(filename=script_path.name, summary=summary)
                )

    # Presets.
    for preset_dir in preset_dirs:
        manifest = manifests[preset_dir.name]
        conventions = manifest.get("conventions", [])
        if not isinstance(conventions, list) or not all(
            isinstance(c, str) for c in conventions
        ):
            raise DocsError(
                f"Preset '{preset_dir.name}' conventions must be a list of strings, "
                f"got: {conventions!r}"
            )
        model.presets.append(
            PresetDoc(
                name=manifest.get("name", preset_dir.name),
                description=str(manifest.get("description", "")).strip(),
                version=str(manifest.get("version", "0.0.0")),
                is_persona=not manifest.get("base_settings", True)
                or preset_dir.name.startswith("persona-"),
                skills=tuple(_shipped_skills(manifest, core_skills)),
                agents=tuple(_shipped_agents(manifest, core_agents)),
                hooks=tuple(_shipped_hooks(manifest)),
                conventions=tuple(conventions),
            )
        )
    model.presets.sort(key=lambda p: (p.is_persona, p.name))

    return model


def _script_summary(script_path: Path) -> str:
    try:
        tree = ast.parse(script_path.read_text(encoding="utf-8"))
    except SyntaxError:
        return ""
    docstring = ast.get_docstring(tree)
    return docstring.strip().split("\n", 1)[0].strip() if docstring else ""


def _cross_validate_hook(name: str, summary: str, events: tuple[str, ...]) -> None:
    """Fail if a hook's docstring claims an event its wiring contradicts.

    Only a *recognized* event token is checked. A descriptive prefix such as
    "Pre-edit" (protect-files) is prose, not a claimed event, and is left alone.
    """
    claimed = _claimed_event(summary)
    if claimed is None or claimed not in KNOWN_EVENTS:
        return
    if not events:
        raise DocsError(
            f"Hook '{name}' docstring claims event '{claimed}' but the hook is not "
            "wired to any event in the settings. Wire it, or drop the event name "
            "from the docstring's first line."
        )
    if claimed not in events:
        raise DocsError(
            f"Hook '{name}' docstring claims event '{claimed}' but its wiring runs "
            f"it on {', '.join(events)}. Fix the docstring or the settings so they "
            "agree."
        )


# --------------------------------------------------------------------------- #
# Marker rewriting
# --------------------------------------------------------------------------- #


_BEGIN_ANY_RE = re.compile(r"<!-- BEGIN GENERATED: ([A-Za-z0-9_-]+) -->")
_END_ANY_RE = re.compile(r"<!-- END GENERATED: ([A-Za-z0-9_-]+) -->")


def rewrite_markers(text: str, blocks: dict[str, str]) -> str:
    """Replace the content inside each GENERATED marker with blocks[id].

    A marker id present in the text with no registered block is an error (a stale
    marker). Registered blocks with no marker in this file are fine — a file uses
    whatever subset of ids it declares. Idempotent: the replacement content is
    stored without a trailing newline and wrapped identically each run.

    Two integrity guards, since these markers gate the whole doc pipeline:
    a block whose content contains its own END marker literal would truncate its
    own region on the next run (unbounded growth), and a half-deleted or
    id-mismatched marker pair would silently be skipped. Both raise DocsError.
    """
    seen: set[str] = set()

    def _replace(match: re.Match) -> str:
        marker_id = match.group("id")
        seen.add(marker_id)
        if marker_id not in blocks:
            raise DocsError(
                f"GENERATED marker '{marker_id}' has no registered content; "
                "remove the marker or add a block for it in build_docs.py."
            )
        body = blocks[marker_id].strip("\n")
        if f"<!-- END GENERATED: {marker_id} -->" in body:
            raise DocsError(
                f"Generated block '{marker_id}' contains its own END marker "
                "literal; block content cannot include the marker syntax."
            )
        return (
            f"<!-- BEGIN GENERATED: {marker_id} -->\n"
            f"{body}\n"
            f"<!-- END GENERATED: {marker_id} -->"
        )

    result = _MARKER_RE.sub(_replace, text)

    # Any BEGIN/END marker left in the text that wasn't part of a matched pair is
    # orphaned or id-mismatched (e.g. a deleted END, or BEGIN `x` / END `y`).
    orphaned = (
        set(_BEGIN_ANY_RE.findall(result)) | set(_END_ANY_RE.findall(result))
    ) - seen
    if orphaned:
        raise DocsError(
            "Unpaired or id-mismatched GENERATED marker(s): "
            f"{', '.join(sorted(orphaned))}. Each needs a matching BEGIN/END pair "
            "with an identical id."
        )
    return result


# --------------------------------------------------------------------------- #
# Renderers — shared table builders
# --------------------------------------------------------------------------- #


def _availability(presets: tuple[str, ...], all_project_presets: set[str]) -> str:
    """Render a component's preset availability compactly ('all' when universal)."""
    if not presets:
        return "—"
    covered = set(presets)
    if all_project_presets and all_project_presets.issubset(covered):
        extra = sorted(covered - all_project_presets)
        return "all" + (f" + {', '.join(extra)}" if extra else "")
    return ", ".join(sorted(covered))


def _project_preset_names(model: DocsModel) -> set[str]:
    return {p.name for p in model.presets if not p.is_persona}


def render_skills_table(skills: list[SkillDoc], model: DocsModel) -> str:
    """One-line-per-skill summary table (name · summary · availability)."""
    project = _project_preset_names(model)
    rows = ["| Skill | Summary | Presets |", "| --- | --- | --- |"]
    for skill in skills:
        avail = _availability(skill.presets, project)
        tag = " *(override)*" if skill.overrides_core else ""
        rows.append(
            f"| `/{skill.name}`{tag} | {_escape_cell(_first_sentence(skill.description))} "
            f"| {avail} |"
        )
    return "\n".join(rows)


def render_agents_table(agents: list[AgentDoc], model: DocsModel) -> str:
    project = _project_preset_names(model)
    rows = ["| Agent | Role | Skills | Presets |", "| --- | --- | --- | --- |"]
    for agent in agents:
        skills = ", ".join(f"`{s}`" for s in agent.skills_add) or "—"
        avail = _availability(agent.presets, project)
        tag = " *(override)*" if agent.overrides_core else ""
        rows.append(f"| **{agent.name}**{tag} | `{agent.role}` | {skills} | {avail} |")
    return "\n".join(rows)


def render_hooks_table(hooks: list[HookDoc], model: DocsModel) -> str:
    project = _project_preset_names(model)
    rows = ["| Hook | Event | Summary | Presets |", "| --- | --- | --- | --- |"]
    for hook in hooks:
        events = ", ".join(f"`{e}`" for e in hook.events) or "—"
        avail = _availability(hook.presets, project)
        rows.append(
            f"| `{hook.name}` | {events} | {_escape_cell(hook.summary)} | {avail} |"
        )
    return "\n".join(rows)


def render_presets_table(presets: list[PresetDoc]) -> str:
    rows = [
        "| Preset | Kind | Skills | Agents | Conventions |",
        "| --- | --- | --- | --- | --- |",
    ]
    for preset in presets:
        kind = "persona" if preset.is_persona else "project"
        conventions = "; ".join(preset.conventions) or "—"
        rows.append(
            f"| **`{preset.name}`** | {kind} | {len(preset.skills)} | "
            f"{len(preset.agents)} | {_escape_cell(conventions)} |"
        )
    return "\n".join(rows)


def render_methodology_table(docs: list[MethodologyDoc]) -> str:
    rows = ["| Document | Summary |", "| --- | --- |"]
    for doc in docs:
        rows.append(
            f"| [`{doc.filename}`](../../core/docs/{doc.filename}) "
            f"| {_escape_cell(doc.summary)} |"
        )
    return "\n".join(rows)


def render_scripts_table(scripts: list[ScriptDoc]) -> str:
    rows = ["| Script | Purpose |", "| --- | --- |"]
    for script in scripts:
        rows.append(f"| `scripts/{script.filename}` | {_escape_cell(script.summary)} |")
    return "\n".join(rows)


def render_counts(model: DocsModel) -> str:
    """The headline count line (single source for the README banner)."""
    core_skills = sum(1 for s in model.skills if s.source == "core")
    core_agents = sum(1 for a in model.agents if a.source == "core")
    hooks = len(model.hooks)
    project = sum(1 for p in model.presets if not p.is_persona)
    persona = sum(1 for p in model.presets if p.is_persona)
    return (
        f"**{core_skills} universal skills · {core_agents} core agents · {hooks} hooks · "
        f"{project} project presets · {persona} persona plugins**"
    )


# --------------------------------------------------------------------------- #
# Renderers — full catalog pages
# --------------------------------------------------------------------------- #


def _catalog_header(title: str, intro: str) -> list[str]:
    return [_DO_NOT_EDIT, "", f"# {title}", "", intro, ""]


def render_skills_page(model: DocsModel) -> str:
    core = [s for s in model.skills if s.source == "core"]
    preset = [s for s in model.skills if s.source != "core"]
    lines = _catalog_header(
        "Skills Reference",
        "Every skill available in the plugin, parsed from each skill's "
        "`SKILL.md` frontmatter. Universal skills ship with every preset; preset "
        "skills ship only where their preset is installed.",
    )
    lines += ["## Universal skills", "", render_skills_table(core, model), ""]
    if preset:
        lines += ["## Preset skills", "", render_skills_table(preset, model), ""]
    lines += ["## Full descriptions", ""]
    for skill in model.skills:
        origin = "universal" if skill.source == "core" else f"`{skill.source}` preset"
        override = (
            " — overrides the core skill of the same name"
            if skill.overrides_core
            else ""
        )
        lines += [
            f"### `/{skill.name}`",
            "",
            f"*{origin}{override}*",
            "",
            skill.description,
            "",
        ]
    return "\n".join(lines).rstrip() + "\n"


def render_agents_page(model: DocsModel) -> str:
    lines = _catalog_header(
        "Agents Reference",
        "Specialized subagent roles, parsed from each agent's `AGENT.md` "
        "frontmatter. A preset agent with the same name as a core agent replaces "
        "it (override semantics, not merge).",
    )
    lines += ["## All agents", "", render_agents_table(model.agents, model), ""]
    lines += ["## Details", ""]
    for agent in model.agents:
        origin = "core" if agent.source == "core" else f"`{agent.source}` preset"
        skills = ", ".join(f"`{s}`" for s in agent.skills_add) or "none"
        lines += [
            f"### {agent.name}",
            "",
            f"*{origin} · role `{agent.role}` · skills: {skills}*",
            "",
            agent.description,
            "",
        ]
    return "\n".join(lines).rstrip() + "\n"


def render_hooks_page(model: DocsModel) -> str:
    lines = _catalog_header(
        "Hooks Reference",
        "Lifecycle hooks and the events they run on. The event column is derived "
        "from the settings wiring (the authoritative source); the summary is each "
        "hook module's docstring.",
    )
    lines += ["## All hooks", "", render_hooks_table(model.hooks, model), ""]
    lines += ["## Details", ""]
    for hook in model.hooks:
        events = ", ".join(f"`{e}`" for e in hook.events) or "not currently wired"
        matchers = ", ".join(f"`{m}`" for m in hook.matchers) or "—"
        origin = "core" if hook.source == "core" else f"`{hook.source}` preset"
        lines += [
            f"### `{hook.name}`",
            "",
            f"*{origin} · events: {events} · matcher: {matchers}*",
            "",
            hook.summary,
            "",
        ]
    return "\n".join(lines).rstrip() + "\n"


def render_presets_page(model: DocsModel) -> str:
    lines = _catalog_header(
        "Presets Reference",
        "Every preset the marketplace can install, with the skills, agents, "
        "hooks, and conventions each one ships. Project presets configure a "
        "project type; persona plugins are output-style-only.",
    )
    lines += ["## All presets", "", render_presets_table(model.presets), ""]
    lines += ["## Details", ""]
    for preset in model.presets:
        kind = "persona plugin" if preset.is_persona else "project preset"
        lines += [
            f"### `{preset.name}`",
            "",
            f"*{kind} · v{preset.version}*",
            "",
            preset.description or "_no description_",
            "",
        ]
        if preset.conventions:
            lines += ["**Conventions:**", ""]
            lines += [f"- {c}" for c in preset.conventions]
            lines += [""]
        if preset.skills:
            lines += [
                f"**Skills ({len(preset.skills)}):** "
                + ", ".join(f"`{s}`" for s in preset.skills),
                "",
            ]
        if preset.agents:
            lines += [
                f"**Agents ({len(preset.agents)}):** "
                + ", ".join(f"`{a}`" for a in preset.agents),
                "",
            ]
        if preset.hooks:
            lines += [
                f"**Hooks ({len(preset.hooks)}):** "
                + ", ".join(f"`{h}`" for h in preset.hooks),
                "",
            ]
    return "\n".join(lines).rstrip() + "\n"


def render_methodology_page(model: DocsModel) -> str:
    lines = _catalog_header(
        "Methodology Reference",
        "The working-method docs bundled into every preset under `docs/`. Each "
        "is summarized from its source file in `core/docs/`.",
    )
    lines += [render_methodology_table(model.methodology), ""]
    for doc in model.methodology:
        lines += [f"## {doc.title}", "", doc.summary, ""]
    return "\n".join(lines).rstrip() + "\n"


# --------------------------------------------------------------------------- #
# Marker block registries
# --------------------------------------------------------------------------- #


def readme_blocks(model: DocsModel) -> dict[str, str]:
    """GENERATED marker blocks for the root README."""
    core_skills = [s for s in model.skills if s.source == "core"]
    preset_skills = [s for s in model.skills if s.source != "core"]
    core_agents = [a for a in model.agents if a.source == "core"]
    preset_agents = [a for a in model.agents if a.source != "core"]
    return {
        "counts": render_counts(model),
        "skills-table": render_skills_table(core_skills, model),
        "preset-skills-table": render_skills_table(preset_skills, model),
        "agents-core-table": render_agents_table(core_agents, model),
        "agents-preset-table": render_agents_table(preset_agents, model),
        "hooks-table": render_hooks_table(model.hooks, model),
        "presets-table": render_presets_table(model.presets),
        "methodology-table": render_methodology_table(model.methodology),
    }


def wiring_blocks(model: DocsModel) -> dict[str, str]:
    """GENERATED marker blocks for docs/reference/build-and-wiring.md."""
    return {
        "scripts-table": render_scripts_table(model.scripts),
        "hooks-wiring-table": render_hooks_table(model.hooks, model),
    }


# --------------------------------------------------------------------------- #
# Dist README rendering (imported by build_preset)
# --------------------------------------------------------------------------- #


def render_preset_readme(
    *,
    name: str,
    description: str,
    skills: list[SkillDoc],
    agents: list[AgentDoc],
    conventions: tuple[str, ...] = (),
) -> str:
    """Render a rich README for a built plugin from its shipped components.

    Kept import-light so build_preset can call it with whatever it assembled.
    """
    lines = [f"# {name}", "", description, ""]
    if conventions:
        lines += ["## Conventions", ""]
        lines += [f"- {c}" for c in conventions]
        lines += [""]
    if skills:
        lines += ["## Skills", ""]
        lines += ["| Skill | Summary |", "| --- | --- |"]
        for skill in sorted(skills, key=lambda s: s.name):
            lines.append(
                f"| `/{_escape_cell(skill.name)}` "
                f"| {_escape_cell(_first_sentence(skill.description))} |"
            )
        lines.append("")
    if agents:
        lines += ["## Agents", ""]
        lines += ["| Agent | Role | Summary |", "| --- | --- | --- |"]
        for agent in sorted(agents, key=lambda a: a.name):
            lines.append(
                f"| {_escape_cell(agent.name)} | `{_escape_cell(agent.role)}` "
                f"| {_escape_cell(_first_sentence(agent.description))} |"
            )
        lines.append("")
    lines += [
        "## CLAUDE.md Template",
        "",
        "Copy the following into your project's `CLAUDE.md` to reference this plugin:",
        "",
        "```",
        "# Project Name",
        "",
        "## Plugins",
        "",
        f"This project uses the {name} plugin for Claude Code configuration.",
        "",
        "## Methodology",
        "",
        "See plugin documentation for TDD, root cause tracing, and subagent development processes.",
        "```",
        "",
    ]
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# Top-level generate / write / check
# --------------------------------------------------------------------------- #


def generate(root: Path) -> dict[Path, str]:
    """Return {path: desired content} for every generated doc."""
    model = build_model(root)
    reference = root / "docs" / "reference"
    outputs: dict[Path, str] = {
        reference / "skills.md": render_skills_page(model),
        reference / "agents.md": render_agents_page(model),
        reference / "hooks.md": render_hooks_page(model),
        reference / "presets.md": render_presets_page(model),
        reference / "methodology.md": render_methodology_page(model),
    }

    readme_path = root / "README.md"
    if readme_path.exists():
        outputs[readme_path] = rewrite_markers(
            readme_path.read_text(encoding="utf-8"), readme_blocks(model)
        )

    wiring_path = reference / "build-and-wiring.md"
    if wiring_path.exists():
        outputs[wiring_path] = rewrite_markers(
            wiring_path.read_text(encoding="utf-8"), wiring_blocks(model)
        )

    return outputs


def write_docs(root: Path) -> list[Path]:
    """Write all generated docs to disk; return the paths written."""
    outputs = generate(root)
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return sorted(outputs)


def check_docs(root: Path) -> list[Path]:
    """Return the paths whose on-disk content is stale relative to the model."""
    stale: list[Path] = []
    for path, content in generate(root).items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            stale.append(path)
    return sorted(stale)


def main(argv: list[str] | None = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    root = Path.cwd()
    if "--check" in argv:
        stale = check_docs(root)
        if stale:
            print(
                "Documentation is stale — run `make docs` and commit:", file=sys.stderr
            )
            for path in stale:
                print(f"  - {path.relative_to(root)}", file=sys.stderr)
            return 1
        print("Documentation is up to date.")
        return 0
    written = write_docs(root)
    print(f"Generated {len(written)} documentation file(s):")
    for path in written:
        print(f"  - {path.relative_to(root)}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except DocsError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc
