"""Fail when a plugin's shipped output changed without a version bump.

The rest of the gate proves a change is correct. This proves it will actually
be delivered: `claude plugin update` decides there is something to offer by
comparing the manifest version, so a plugin whose content changed without a
bump merges green, promotes green, and silently reaches nobody.

Compares `plugins/<name>` — the real served directory, there is no `dist/`
under the flat plugin tree — against a base ref, excluding every path
`scripts.stamp.owned_paths()` says the stamper owns. Generated content is a
pure function of hand-authored content, so any real (owner-facing) change
already trips this gate through the hand-written source that produced it;
diffing the generated bytes too would mean a purely cosmetic formatting tweak
inside `stamp.py` demands nine simultaneous version bumps across every plugin
for zero semantic change.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

from scripts.stamp import StampError, owned_paths

DEFAULT_BASE = "origin/main"


def run_git(repo: Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", *args], cwd=str(repo), capture_output=True, text=True, check=False
    )


def resolve_base(repo: Path, base: str) -> str:
    """Full sha for `base`, or raise — never silently skip.

    A gate that quietly does nothing when it cannot find its baseline is worse
    than no gate: it reports success having compared nothing.
    """
    result = run_git(repo, "rev-parse", "--verify", "--quiet", f"{base}^{{commit}}")
    sha = result.stdout.strip()
    if not sha:
        raise LookupError(
            f"base ref {base!r} not found. CI must check out enough history to "
            f"resolve it (actions/checkout defaults to depth 1); locally, fetch it."
        )
    return sha


def shipped_plugins(repo: Path) -> list[str]:
    """Every plugin directory in the working tree: one with its own manifest."""
    plugins = repo / "plugins"
    if not plugins.is_dir():
        return []
    return sorted(
        d.name
        for d in plugins.iterdir()
        if d.is_dir() and (d / ".claude-plugin" / "plugin.json").is_file()
    )


def _stamper_exclusions(repo: Path) -> list[str]:
    """Repo-relative POSIX paths for every file `scripts.stamp` generates.

    `owned_paths()` returns absolute paths for the tree rooted at `repo`; `git
    diff` pathspecs need repo-relative POSIX paths, so each is converted with
    `relative_to(repo)` against the exact same `repo` object used to build
    them — anything looser risks a path that silently fails to match.
    """
    return sorted(path.relative_to(repo).as_posix() for path in owned_paths(repo))


def output_changed(repo: Path, base: str, plugin: str, exclusions: list[str]) -> bool:
    """True when `plugin`'s owner-facing shipped output differs from `base`.

    Two exclusions on top of the plugin's own directory:

    * every stamper-owned path (see module docstring) — a plugin's version
      only needs to move for hand-authored changes, not for the generated
      files those changes cause to be re-rendered.
    * `plugins/<plugin>/machinery` — vendored engine payload (scripts + their
      tests), not a skill, agent, or hook an owner invokes. Its churn is
      versioned by its upstream repo; requiring a bump for every sync would
      turn routine consolidation into a release event.
    """
    pathspecs = [f":(exclude){path}" for path in exclusions]
    pathspecs.append(f":(exclude)plugins/{plugin}/machinery")
    return (
        run_git(
            repo, "diff", "--quiet", base, "--", f"plugins/{plugin}", *pathspecs
        ).returncode
        != 0
    )


def manifest_version(repo: Path, plugin: str, ref: str | None = None) -> str | None:
    """Declared version at `ref` (or the working tree when ref is None)."""
    relative = f"plugins/{plugin}/.claude-plugin/plugin.json"
    if ref is None:
        path = repo / relative
        if not path.is_file():
            return None
        text = path.read_text(encoding="utf-8")
    else:
        result = run_git(repo, "show", f"{ref}:{relative}")
        if result.returncode != 0:
            return None
        text = result.stdout
    try:
        return json.loads(text).get("version")
    except (json.JSONDecodeError, AttributeError):
        return None


def find_missing_bumps(repo: Path, base: str = DEFAULT_BASE) -> list[str]:
    """Plugins whose shipped output changed since `base` without a version bump.

    A plugin absent from `base` is new — there is no prior version to bump
    from. A plugin absent from the working tree was deleted, and a deleted
    plugin needs no bump either.
    """
    base_sha = resolve_base(repo, base)
    exclusions = _stamper_exclusions(repo)
    missing = []
    for plugin in shipped_plugins(repo):
        if not output_changed(repo, base_sha, plugin, exclusions):
            continue
        released = manifest_version(repo, plugin, base_sha)
        if released is None:
            continue  # new plugin
        current = manifest_version(repo, plugin)
        if current is None:
            continue  # being removed
        if current == released:
            missing.append(plugin)
    return missing


# --------------------------------------------------------------------------
# Bump level
#
# A removed skill and a corrected typo are not the same event to an owner: a
# removal changes the trigger surface, so their invocations silently stop
# matching. Only the mechanically visible part of that judgement is enforced
# here — the component inventory a plugin ships. Behavioural breaks (a hook
# that now blocks where it did not) still need a human call; the policy in
# CLAUDE.md says so rather than pretending this covers them.
#
# A skill, agent, or hook that *moves* from one plugin to another (newly
# reachable now that the tree is flat) needs no separate handling: the
# component inventory below is scoped to one plugin's own subtree, at two
# points in time. A move makes it vanish from the losing plugin's own
# inventory exactly like a deletion would — `before - after` is non-empty
# there regardless of where the component reappears — so it already demands
# a major bump for the plugin that lost it, via the same rule that catches
# any other removal. See TestCrossPluginMove in the test file.
# --------------------------------------------------------------------------

LEVELS = ("patch", "minor", "major")


def _components_at(repo: Path, plugin: str, ref: str | None) -> set[str]:
    """Skills, agents, and hook scripts a plugin ships — its owner-facing surface.

    Underscore-prefixed hook files are shared library modules, not
    capabilities (see `plugins/workbench/hooks/scripts/_git_baseline.py`), and
    are excluded for the same reason hook discovery and the fail-open scan
    exclude them.
    """
    prefix = f"plugins/{plugin}/"
    if ref is None:
        base = repo / "plugins" / plugin
        paths = (
            [str(p.relative_to(repo)) for p in base.rglob("*")] if base.is_dir() else []
        )
    else:
        result = run_git(repo, "ls-tree", "-r", "--name-only", ref, "--", prefix)
        paths = result.stdout.splitlines() if result.returncode == 0 else []

    components = set()
    for path in paths:
        parts = Path(path).relative_to(f"plugins/{plugin}").parts if path.startswith(prefix) else ()
        if len(parts) >= 2 and parts[0] in ("skills", "agents"):
            components.add(f"{parts[0]}/{parts[1]}")
        elif len(parts) == 3 and parts[0] == "hooks" and parts[1] == "scripts":
            if not parts[2].startswith("_"):
                components.add(f"hooks/{parts[2]}")
    return components


def required_level(repo: Path, plugin: str, base_sha: str) -> str:
    before = _components_at(repo, plugin, base_sha)
    after = _components_at(repo, plugin, None)
    if before - after:
        return "major"
    if after - before:
        return "minor"
    return "patch"


def _parts(version: str | None) -> tuple[int, int, int] | None:
    if not version:
        return None
    chunks = version.split(".")
    if len(chunks) != 3 or not all(c.isdigit() for c in chunks):
        return None
    major, minor, patch = (int(c) for c in chunks)
    return major, minor, patch


def actual_level(released: str | None, current: str | None) -> str | None:
    """Which component moved, or None when the version did not advance.

    Pre-1.0, a minor bump IS the breaking signal — `0.1.3 -> 0.2.0` — so it
    satisfies a `major` requirement. Demanding `1.0.0` to drop a skill from a
    0.x plugin would force a release meaning nobody intends.
    """
    before, after = _parts(released), _parts(current)
    if before is None or after is None or after <= before:
        return None
    if after[0] != before[0]:
        return "major"
    if after[1] != before[1]:
        return "major" if before[0] == 0 else "minor"
    return "patch"


def find_level_violations(
    repo: Path, base: str = DEFAULT_BASE
) -> list[tuple[str, str, str]]:
    """(plugin, required, actual) where the bump is too small for the change."""
    base_sha = resolve_base(repo, base)
    exclusions = _stamper_exclusions(repo)
    violations = []
    for plugin in shipped_plugins(repo):
        if not output_changed(repo, base_sha, plugin, exclusions):
            continue
        released = manifest_version(repo, plugin, base_sha)
        current = manifest_version(repo, plugin)
        if released is None or current is None:
            continue
        actual = actual_level(released, current)
        if actual is None:
            continue  # no bump at all — find_missing_bumps owns that message
        required = required_level(repo, plugin, base_sha)
        if LEVELS.index(actual) < LEVELS.index(required):
            violations.append((plugin, required, actual))
    return violations


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", default=".")
    parser.add_argument("--base", default=DEFAULT_BASE)
    args = parser.parse_args(argv)

    repo = Path(args.repo)
    try:
        missing = find_missing_bumps(repo, args.base)
        levels = find_level_violations(repo, args.base)
    except LookupError as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1
    except StampError as error:
        print(f"ERROR: could not resolve stamper-owned paths: {error}", file=sys.stderr)
        return 1

    if not missing and not levels:
        print(f"version-bump gate: no unbumped plugins against {args.base}.")
        return 0

    if levels:
        print(
            "ERROR: these plugins changed their component surface by more than "
            "their version bump claims:",
            file=sys.stderr,
        )
        for plugin, required, actual in levels:
            print(
                f"  {plugin}: needs a {required} bump, got {actual} "
                f"({manifest_version(repo, plugin)})",
                file=sys.stderr,
            )
        print(
            "\nA removed skill, agent, or hook changes what an owner can invoke "
            "(including one that moved to another plugin); an added one is new "
            "capability. See Preset Versioning in CLAUDE.md.",
            file=sys.stderr,
        )
        if not missing:
            return 1
        print("", file=sys.stderr)

    print(
        "ERROR: these plugins ship changed content but declare the same version "
        f"as {args.base}:",
        file=sys.stderr,
    )
    for plugin in missing:
        version = manifest_version(Path(args.repo), plugin)
        print(f"  {plugin} (still {version})", file=sys.stderr)
    print(
        "\nBump each plugin's .claude-plugin/plugin.json version, or the change "
        "merges green and never reaches anyone who has it installed.",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
