"""Stamp every generated file in the flat plugin tree from its hand-written source.

This module is the repo's only build component. There is no composition step and
no ``dist/``: the nine directories under ``plugins/`` *are* the served plugins.
What remains is a stamper — it reads the hand-written truth in the tree and
writes the derived files that must agree with it.

The hand-written truth is exactly three things:

* ``plugins/<name>/.claude-plugin/plugin.json`` — name, version, description, and
  an optional ``conventions`` list. It carries no membership lists: a plugin
  ships the skills in its own ``skills/`` and the agents in its own ``agents/``.
* Component frontmatter — ``SKILL.md`` / ``AGENT.md``.
* A hook's own ``WORKSHOP_HOOK`` declaration, read statically with ``ast``.
  Dropping a script into ``plugins/<name>/hooks/scripts/`` *is* the wiring.

Everything else in the twelve owned path classes (see ``owned_paths``) is
derived. Each generated file carries a ``scripts/stamp.py`` marker — a
``_generated`` key in JSON, a comment line in Markdown/shell/Python — and the
stamper refuses to overwrite an existing file that lacks one, so a mis-mapped
output can never silently consume hand-written work.

Rendering is pure and deterministic (everything sorted), so ``stamp --check``
can render in memory, diff against the tree, and fail the gate without writing.
That gate runs in ``make test`` and in CI.
"""

from __future__ import annotations

import argparse
import ast
import difflib
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

from scripts.smoke_test import _parse_frontmatter

# --------------------------------------------------------------------------- #
# Markers
# --------------------------------------------------------------------------- #

#: The string every stamped file carries. The overwrite refusal keys on it.
GENERATED_MARKER = "scripts/stamp.py"

_JSON_MARKER_KEY = "_generated"

_MD_MARKER = (
    f"<!-- Generated by {GENERATED_MARKER} — do not edit by hand.\n"
    "     Run `make stamp` after changing a plugin, skill, hook, or agent. -->"
)

_COMMENT_MARKER = (
    f"# Generated by {GENERATED_MARKER} — do not edit by hand. The canonical "
    "copy lives\n# under plugins/workbench/hooks/; edit that and re-run `make stamp`."
)

# One-time cutover adoption. The composition build wrote these files with no
# machine-readable marker the stamper can recognise, so on its first run the
# refusal would fire on predecessor output rather than on hand-written work.
# Both entries below become inert the moment they are stamped (they then carry
# GENERATED_MARKER), and this set can be deleted once the cutover has landed.
_PREDECESSOR_MARKERS = ("scripts/build_docs.py", "scripts/build_marketplace.py")
_CUTOVER_ADOPTED = frozenset(
    {
        ".claude-plugin/marketplace.json",
        ".agents/plugins/marketplace.json",
        "plugins/workbench/hooks/hooks.json",
    }
)

# --------------------------------------------------------------------------- #
# Constants
# --------------------------------------------------------------------------- #

# Hook lifecycle events the platforms actually dispatch. A WORKSHOP_HOOK naming
# anything else is a typo that would generate wiring which never fires, so it is
# a hard failure rather than a silently dead entry.
KNOWN_EVENTS = frozenset(
    {
        "PreToolUse",
        "PostToolUse",
        "UserPromptSubmit",
        "Notification",
        "Stop",
        "SubagentStart",
        "SubagentStop",
        "SessionStart",
        "SessionEnd",
        "PreCompact",
        "ConfigChange",
    }
)

# The runners a hook can declare. "bash" runs the script under the plugin's
# python3; "uv" runs it under `uv run` so a PEP-723 script block is honoured;
# "vault" routes through run-vault-hook.sh, which exits before starting any
# interpreter unless the session is inside a vault (#667). Vault hooks ship in
# workbench, so every consumer dispatches them — the guard is what keeps that
# free for everyone else.
_RUNNERS = frozenset({"bash", "uv", "vault"})

# Marketplace identity. Held here rather than read back out of the generated
# marketplace files, which would make the stamper's input its own output.
MARKETPLACE_NAME = "the-workshop"
MARKETPLACE_OWNER = {"name": "Charles Coonce"}
MARKETPLACE_DISPLAY_NAME = "The Workshop"

# The project-specific doc under a plugin's docs/ that is not methodology.
_PROJECT_DOC = "project.md"

# `run-hook.sh [--flags] <script>.py` OR a direct `hooks/scripts/<script>.py`.
# Both forms appear in the wild: the generated wiring always routes through
# run-hook.sh, but hand-written and vendored settings still use the direct form
# (upstream issue #646), and a docs table that silently drops those rows claims
# a hook is unwired when it is not.
_HOOK_SCRIPT_RE = re.compile(
    r"(?:run-hook\.sh\s+(?:--[\w-]+\s+)*|hooks/scripts/)([\w.-]+\.py)"
)

# A GENERATED marker pair, matched by id so the same id can be filled anywhere.
# The body is captured lazily and may be empty, so the initial adjacent
# BEGIN/END state (no content yet) still matches and gets filled.
_MARKER_RE = re.compile(
    r"<!-- BEGIN GENERATED: (?P<id>[A-Za-z0-9_-]+) -->\n"
    r"(?P<body>.*?)"
    r"<!-- END GENERATED: (?P=id) -->",
    re.DOTALL,
)


class StampError(Exception):
    """Raised when stamping hits malformed input or would clobber hand-written work."""


# --------------------------------------------------------------------------- #
# Model
# --------------------------------------------------------------------------- #


@dataclass(frozen=True)
class SkillDoc:
    """A skill's documented surface, parsed from its SKILL.md frontmatter."""

    name: str
    description: str
    plugin: str


@dataclass(frozen=True)
class AgentDoc:
    """An agent's documented surface, parsed from its AGENT.md frontmatter."""

    name: str
    description: str
    role: str
    skills_add: tuple[str, ...]
    plugin: str


@dataclass(frozen=True)
class HookDoc:
    """A hook script's documented surface: docstring summary + emitted wiring."""

    name: str
    summary: str
    plugin: str
    events: tuple[str, ...] = ()
    matchers: tuple[str, ...] = ()


@dataclass(frozen=True)
class HookWiring:
    """One hook's WORKSHOP_HOOK declaration, validated."""

    script: str
    event: str
    matcher: str
    runner: str


@dataclass(frozen=True)
class MethodologyDoc:
    """A methodology doc under a plugin's docs/ (title + first paragraph)."""

    filename: str
    title: str
    summary: str
    plugin: str


@dataclass(frozen=True)
class ScriptDoc:
    """A tooling script under scripts/ (module docstring first line)."""

    filename: str
    summary: str


@dataclass(frozen=True)
class PluginDoc:
    """One plugin directory: its manifest plus the components it actually ships."""

    name: str
    directory: Path
    version: str
    description: str
    conventions: tuple[str, ...]
    manifest: dict
    skills: tuple[SkillDoc, ...]
    agents: tuple[AgentDoc, ...]
    hooks: tuple[HookDoc, ...]
    hooks_json: str | None
    is_persona: bool
    wants_run_hook: bool


@dataclass(frozen=True)
class PlatformCellDoc:
    """One platform's support status for a component class."""

    status: str  # works | partial | inert | unverified
    note: str
    compat: str  # COMPATIBILITY.md section the status is grounded in


@dataclass(frozen=True)
class PlatformComponentDoc:
    """A component class row in the platform-support matrix."""

    name: str
    cells: dict[str, PlatformCellDoc]  # keyed by platform name


@dataclass(frozen=True)
class PlatformSupportDoc:
    """The per-platform capability matrix, from scripts/platform-support.json.

    COMPATIBILITY.md holds the evidence; this file holds the verdicts in a
    shape the doc generator can render, so the README's platform claims are
    drift-gated like every other generated region.
    """

    platforms: tuple[str, ...]
    components: tuple[PlatformComponentDoc, ...]


@dataclass
class StampModel:
    """The full parsed model every owned path is rendered from."""

    plugins: list[PluginDoc] = field(default_factory=list)
    skills: list[SkillDoc] = field(default_factory=list)
    agents: list[AgentDoc] = field(default_factory=list)
    hooks: list[HookDoc] = field(default_factory=list)
    methodology: list[MethodologyDoc] = field(default_factory=list)
    scripts: list[ScriptDoc] = field(default_factory=list)
    platform_support: PlatformSupportDoc | None = None
    persona_plumbing: dict[str, str] = field(default_factory=dict)


# --------------------------------------------------------------------------- #
# Parsing helpers
# --------------------------------------------------------------------------- #


# Abbreviations whose internal period must not be treated as a sentence end.
_ABBREVIATIONS = frozenset(
    {"e.g", "i.e", "etc", "vs", "cf", "approx", "al", "no", "fig", "eq", "ca"}
)


def _first_sentence(text: str) -> str:
    """Return the first sentence of a description for summary tables.

    A period ends the sentence only when the word before it isn't a known
    abbreviation ("e.g.", "etc.") or a bare number/letter ("Python 3." /
    "point A."), so summaries aren't truncated mid-clause.
    """
    text = " ".join(text.split())
    for match in re.finditer(r"[.!?](\s|$)", text):
        end = match.start()
        token = text[:end].rsplit(" ", 1)[-1].rstrip(".").lower()
        if token in _ABBREVIATIONS:
            continue
        if len(token) <= 1 and token.isalnum():
            continue
        return text[: end + 1].strip()
    return text


def _escape_cell(text: str) -> str:
    """Escape a value for a Markdown table cell (pipes, newlines)."""
    return " ".join(text.split()).replace("|", "\\|")


def _read_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise StampError(f"Expected JSON not found: {path}") from exc
    except ValueError as exc:
        raise StampError(f"Invalid JSON in {path}: {exc}") from exc


def _load_frontmatter(md_path: Path, label: str) -> dict:
    """Parse frontmatter or raise a StampError naming the offending file."""
    frontmatter = _parse_frontmatter(md_path.read_text(encoding="utf-8"))
    if frontmatter is None:
        raise StampError(f"{label} '{md_path}' has no valid frontmatter")
    return frontmatter


def _require_str(frontmatter: dict, field_name: str, label: str) -> str:
    """Return a required string field, or raise StampError naming the file.

    Guards against the frontmatter parser returning a non-string (e.g. a dict
    when a plain multiline value's continuation line contains a colon) — that
    must fail loudly rather than ship a ``{...}`` repr in the docs.
    """
    value = frontmatter.get(field_name)
    if not isinstance(value, str) or not value.strip():
        raise StampError(f"{label} missing or non-string field '{field_name}'")
    return value.strip()


def _parse_skill(skill_dir: Path, plugin: str) -> SkillDoc:
    """Parse one skill directory into a SkillDoc, failing fast on bad metadata."""
    skill_md = skill_dir / "SKILL.md"
    if not skill_md.exists():
        raise StampError(f"Skill '{skill_dir.name}' has no SKILL.md at {skill_md}")
    frontmatter = _load_frontmatter(skill_md, "Skill")
    label = f"Skill '{skill_dir.name}/SKILL.md'"
    return SkillDoc(
        name=_require_str(frontmatter, "name", label),
        description=_require_str(frontmatter, "description", label),
        plugin=plugin,
    )


def _parse_agent(agent_dir: Path, plugin: str) -> AgentDoc:
    """Parse one agent directory into an AgentDoc, failing fast on bad metadata."""
    agent_md = agent_dir / "AGENT.md"
    if not agent_md.exists():
        raise StampError(f"Agent '{agent_dir.name}' has no AGENT.md at {agent_md}")
    frontmatter = _load_frontmatter(agent_md, "Agent")
    label = f"Agent '{agent_dir.name}/AGENT.md'"
    skills_config = frontmatter.get("skills", {})
    skills_add: tuple[str, ...] = ()
    if isinstance(skills_config, dict):
        add = skills_config.get("add", [])
        if isinstance(add, list):
            skills_add = tuple(str(s) for s in add)
    return AgentDoc(
        name=_require_str(frontmatter, "name", label),
        description=_require_str(frontmatter, "description", label),
        role=_require_str(frontmatter, "role", label),
        skills_add=skills_add,
        plugin=plugin,
    )


def _parse_hook_summary(source: str, filename: str) -> str:
    """Return the first line of a hook module's docstring, failing fast if absent."""
    tree = _parse_python(source, filename)
    docstring = ast.get_docstring(tree)
    if not docstring:
        raise StampError(
            f"Hook '{filename}' has no module docstring; the first line "
            "documents what the hook does and is required for the reference."
        )
    return docstring.strip().split("\n", 1)[0].strip()


def _parse_python(source: str, filename: str) -> ast.Module:
    try:
        return ast.parse(source)
    except SyntaxError as exc:
        raise StampError(f"Hook '{filename}' is not parseable Python: {exc}") from exc


def read_hook_declaration(source: str, filename: str) -> dict | None:
    """Return a module's ``WORKSHOP_HOOK`` literal, or None when it declares none.

    Read statically. Hook scripts read stdin and call ``sys.exit()`` at import
    time, so importing one to inspect an attribute hangs or kills the process
    that inspects it. A module with no top-level ``WORKSHOP_HOOK`` is a shared
    library that happens to live in the hook directory (sibling imports resolve
    there at runtime), not a hook, and is skipped silently.
    """
    tree = _parse_python(source, filename)
    for node in tree.body:
        if isinstance(node, ast.Assign):
            targets = node.targets
        elif isinstance(node, ast.AnnAssign):
            targets = [node.target]
        else:
            continue
        if not any(
            isinstance(target, ast.Name) and target.id == "WORKSHOP_HOOK"
            for target in targets
        ):
            continue
        if node.value is None:
            continue
        try:
            declaration = ast.literal_eval(node.value)
        except ValueError as exc:
            raise StampError(
                f"Hook '{filename}' WORKSHOP_HOOK is not a literal; it must be a "
                "plain dict the stamper can read without executing the module."
            ) from exc
        if not isinstance(declaration, dict):
            raise StampError(
                f"Hook '{filename}' WORKSHOP_HOOK must be a dict, got "
                f"{type(declaration).__name__}."
            )
        return declaration
    return None


def _validate_declaration(filename: str, declaration: dict) -> HookWiring:
    """Turn a raw WORKSHOP_HOOK dict into validated wiring, or fail loudly."""
    event = declaration.get("event")
    if not isinstance(event, str) or not event.strip():
        raise StampError(
            f"Hook '{filename}' WORKSHOP_HOOK has no 'event'; the event name is "
            "the one required key."
        )
    if event not in KNOWN_EVENTS:
        raise StampError(
            f"Hook '{filename}' declares unknown event '{event}'. Wiring generated "
            "for an event no platform dispatches would never fire. Known events: "
            f"{', '.join(sorted(KNOWN_EVENTS))}."
        )
    matcher = declaration.get("matcher", "")
    if not isinstance(matcher, str):
        raise StampError(
            f"Hook '{filename}' WORKSHOP_HOOK 'matcher' must be a string, got "
            f"{type(matcher).__name__}."
        )
    runner = declaration.get("runner", "bash")
    if runner not in _RUNNERS:
        raise StampError(
            f"Hook '{filename}' declares unknown runner {runner!r}; expected one "
            f"of {', '.join(sorted(_RUNNERS))}."
        )
    return HookWiring(script=filename, event=event, matcher=matcher, runner=runner)


def _script_from_command(command: str) -> str | None:
    """Extract the hook script filename from a wiring command string."""
    match = _HOOK_SCRIPT_RE.search(command)
    return match.group(1) if match else None


def _walk_hook_wiring(wiring: dict) -> dict[str, dict[str, set[str]]]:
    """Map hook script name -> {"events": {...}, "matchers": {...}} from hooks.json.

    Reads a plugin's *own* generated wiring, so the docs tables describe the
    file that actually ships rather than a model of it. If a renderer change
    ever stopped emitting an entry, the docs would stop claiming it too.
    """
    found: dict[str, dict[str, set[str]]] = {}
    for event, entries in wiring.get("hooks", {}).items():
        if not isinstance(entries, list):
            continue
        for entry in entries:
            matcher = entry.get("matcher", "")
            for hook in entry.get("hooks", []):
                script = _script_from_command(hook.get("command", ""))
                if not script:
                    continue
                record = found.setdefault(script, {"events": set(), "matchers": set()})
                record["events"].add(event)
                if matcher:
                    record["matchers"].add(matcher)
    return found


def _parse_methodology(doc_path: Path, plugin: str) -> MethodologyDoc:
    """Parse a methodology doc's title (first heading) and first paragraph."""
    lines = doc_path.read_text(encoding="utf-8").split("\n")
    title = doc_path.stem
    summary = ""
    body: list[str] = []
    for line in lines:
        if line.startswith("#") and title == doc_path.stem:
            title = line.lstrip("#").strip()
            continue
        if line.strip() and not line.startswith("#"):
            body.append(line.strip())
        elif body:
            break
    if body:
        summary = " ".join(body)
    return MethodologyDoc(
        filename=doc_path.name, title=title, summary=summary, plugin=plugin
    )


def _script_summary(script_path: Path) -> str:
    try:
        tree = ast.parse(script_path.read_text(encoding="utf-8"))
    except SyntaxError:
        return ""
    docstring = ast.get_docstring(tree)
    return docstring.strip().split("\n", 1)[0].strip() if docstring else ""


# --------------------------------------------------------------------------- #
# Tree walking
# --------------------------------------------------------------------------- #


_BUILD_ARTIFACT_DIRS = frozenset({"__pycache__", ".pytest_cache", ".ruff_cache"})


def _is_build_artifact(path: Path, base: Path) -> bool:
    relative = path.relative_to(base)
    return bool(_BUILD_ARTIFACT_DIRS.intersection(relative.parts)) or path.suffix == ".pyc"


def is_leftover_artifact_dir(component_dir: Path) -> bool:
    """True when a directory's whole content is build artifacts git left behind.

    Switching off a branch that added a component removes its tracked files but
    keeps ignored ones — git will not delete ignored content. The empty shell
    that remains is not a malformed component, it is debris, and reporting it as
    a component names something that does not exist on the current branch.

    An *empty* directory is deliberately not treated as debris: git never
    creates one on checkout, so it can only be hand-made, and that is a real
    mistake worth failing on.
    """
    files = [p for p in component_dir.rglob("*") if p.is_file()]
    return bool(files) and all(_is_build_artifact(p, component_dir) for p in files)


def _component_dirs(parent: Path) -> list[Path]:
    """Component directories under `parent`, skipping build-artifact debris."""
    if not parent.exists():
        return []
    return sorted(
        d for d in parent.iterdir() if d.is_dir() and not is_leftover_artifact_dir(d)
    )


def _plugin_dirs(root: Path) -> list[Path]:
    """Every served plugin: a directory under plugins/ with a hand-written manifest."""
    plugins = root / "plugins"
    if not plugins.exists():
        return []
    return sorted(
        d
        for d in plugins.iterdir()
        if d.is_dir() and (d / ".claude-plugin" / "plugin.json").exists()
    )


def _check_slug_uniqueness(root: Path, plugin_dirs: list[Path]) -> None:
    """Fail if two plugins ship a skill with the same slug.

    `improve-skill` and its siblings resolve a skill by a flat
    ``plugins/*/skills/<slug>/`` glob. Two hits means a tool silently edits one
    copy and ships the other, so the collision has to be a build failure and
    the message has to name both sides.
    """
    seen: dict[str, str] = {}
    for plugin_dir in plugin_dirs:
        for skill_dir in _component_dirs(plugin_dir / "skills"):
            relative = skill_dir.relative_to(root).as_posix()
            previous = seen.get(skill_dir.name)
            if previous is not None:
                raise StampError(
                    f"Skill slug '{skill_dir.name}' is shipped by two plugins: "
                    f"{previous} and {relative}. One plugin per slug — a flat "
                    "slug glob cannot tell the copies apart."
                )
            seen[skill_dir.name] = relative


def _check_plugin_name_uniqueness(root: Path, plugins: list[PluginDoc]) -> None:
    """Fail if two plugin directories advertise the same manifest name.

    Directory names cannot collide — the filesystem sees to that — but the
    `name` inside a manifest is free text, and it is what the marketplace
    advertises and what `/plugin install <name>@the-workshop` resolves. Two
    entries under one name renders a marketplace with a duplicate the installer
    picks between arbitrarily. The old `build_marketplace.py` raised on this;
    the check did not survive the rewrite, so it is restored here.
    """
    seen: dict[str, str] = {}
    for plugin in plugins:
        relative = plugin.directory.relative_to(root).as_posix()
        previous = seen.get(plugin.name)
        if previous is not None:
            raise StampError(
                f"Plugin name '{plugin.name}' is claimed by two directories: "
                f"{previous} and {relative}. The marketplace advertises one "
                "entry per name and the installer cannot tell them apart."
            )
        seen[plugin.name] = relative


def _persona_plumbing(root: Path) -> dict[str, str]:
    """The canonical persona artefacts workbench owns and every persona copies.

    Workbench ships ``inject_persona.py`` it never runs so the five personas
    cannot drift from each other. The cost, accepted with eyes open, is that
    editing persona plumbing bumps workbench's version.
    """
    hooks_dir = root / "plugins" / "workbench" / "hooks"
    plumbing: dict[str, str] = {}
    for name in ("inject_persona.py", "run-hook.sh"):
        source = hooks_dir / name
        if source.exists():
            plumbing[name] = _insert_marker_comment(
                source.read_text(encoding="utf-8"), _COMMENT_MARKER
            )
    return plumbing


def _insert_marker_comment(text: str, marker: str) -> str:
    """Insert a `#` comment marker after a file's leading shebang/comment block.

    Placed after the header rather than at line 1 so a shebang stays executable
    and a PEP-723 ``# /// script`` block stays contiguous. Comments are invisible
    to ``ast``, so a module docstring that follows is still the docstring.
    """
    if marker in text:
        return text
    lines = text.split("\n")
    index = 0
    while index < len(lines) and (
        lines[index].startswith("#") or not lines[index].strip()
    ):
        index += 1
    lines[index:index] = marker.split("\n")
    return "\n".join(lines)


def _hook_sources(plugin_dir: Path, is_persona: bool, plumbing: dict[str, str]) -> dict[str, str]:
    """The hook scripts a plugin ships, as {filename: source text}.

    Includes the copy the stamper is about to write into a persona, so a
    persona's wiring is generated from the same bytes that land on disk instead
    of from whatever a previous run left behind.
    """
    sources: dict[str, str] = {}
    scripts_dir = plugin_dir / "hooks" / "scripts"
    if scripts_dir.exists():
        for path in sorted(scripts_dir.glob("*.py")):
            sources[path.name] = path.read_text(encoding="utf-8")
    if is_persona and "inject_persona.py" in plumbing:
        sources["inject_persona.py"] = plumbing["inject_persona.py"]
    return dict(sorted(sources.items()))


_PLATFORM_STATUSES = frozenset({"works", "partial", "inert", "unverified"})


def _load_platform_support(root: Path) -> PlatformSupportDoc | None:
    """Parse scripts/platform-support.json, or None when the repo ships none."""
    path = root / "scripts" / "platform-support.json"
    if not path.exists():
        return None
    data = _read_json(path)
    platforms = data.get("platforms")
    if not isinstance(platforms, list) or not all(
        isinstance(p, str) for p in platforms
    ):
        raise StampError(f"'{path}' needs a 'platforms' list of platform names")
    components: list[PlatformComponentDoc] = []
    for entry in data.get("components", []):
        name = entry.get("name")
        cells_raw = entry.get("cells")
        if not isinstance(name, str) or not isinstance(cells_raw, dict):
            raise StampError(f"'{path}' component entries need 'name' and 'cells'")
        if set(cells_raw) != set(platforms):
            mismatched = sorted(set(cells_raw) ^ set(platforms))
            raise StampError(
                f"'{path}' component '{name}' cells must cover exactly the "
                f"declared platforms; mismatched: {', '.join(mismatched)}"
            )
        cells: dict[str, PlatformCellDoc] = {}
        for platform, cell in cells_raw.items():
            status = cell.get("status") if isinstance(cell, dict) else None
            if status not in _PLATFORM_STATUSES:
                raise StampError(
                    f"'{path}' component '{name}' platform '{platform}' has "
                    f"invalid status {status!r}; expected one of "
                    f"{', '.join(sorted(_PLATFORM_STATUSES))}"
                )
            cells[platform] = PlatformCellDoc(
                status=status,
                note=str(cell.get("note", "")),
                compat=str(cell.get("compat", "")),
            )
        components.append(PlatformComponentDoc(name=name, cells=cells))
    if not components:
        raise StampError(f"'{path}' declares no components")
    return PlatformSupportDoc(platforms=tuple(platforms), components=tuple(components))


# --------------------------------------------------------------------------- #
# Model assembly
# --------------------------------------------------------------------------- #


def build_model(root: Path) -> StampModel:
    """Parse the flat plugin tree into the model every owned path renders from."""
    model = StampModel()
    model.platform_support = _load_platform_support(root)
    model.persona_plumbing = _persona_plumbing(root)

    plugin_dirs = _plugin_dirs(root)
    _check_slug_uniqueness(root, plugin_dirs)

    for plugin_dir in plugin_dirs:
        model.plugins.append(_build_plugin(root, plugin_dir, model.persona_plumbing))

    _check_plugin_name_uniqueness(root, model.plugins)

    for plugin in model.plugins:
        model.skills.extend(plugin.skills)
        model.agents.extend(plugin.agents)
        model.hooks.extend(plugin.hooks)
    model.skills.sort(key=lambda s: (s.name, s.plugin))
    model.agents.sort(key=lambda a: (a.name, a.plugin))
    model.hooks.sort(key=lambda h: (h.name, h.plugin))

    for plugin_dir in plugin_dirs:
        docs_dir = plugin_dir / "docs"
        if not docs_dir.exists():
            continue
        for doc_path in sorted(docs_dir.glob("*.md")):
            if doc_path.name == _PROJECT_DOC:
                continue
            model.methodology.append(_parse_methodology(doc_path, plugin_dir.name))
    model.methodology.sort(key=lambda d: (d.filename, d.plugin))

    scripts_dir = root / "scripts"
    if scripts_dir.exists():
        for script_path in sorted(scripts_dir.glob("*.py")):
            if script_path.name in ("__init__.py", "__main__.py"):
                continue
            summary = _script_summary(script_path)
            if summary:
                model.scripts.append(
                    ScriptDoc(filename=script_path.name, summary=summary)
                )

    return model


def _build_plugin(root: Path, plugin_dir: Path, plumbing: dict[str, str]) -> PluginDoc:
    """Parse one plugin directory: manifest, components, and its hook wiring."""
    manifest_path = plugin_dir / ".claude-plugin" / "plugin.json"
    manifest = _read_json(manifest_path)
    # No directory-name fallback. `name` is what a marketplace entry advertises
    # and what `/plugin install <name>@the-workshop` resolves; defaulting it
    # would let a manifest that forgot the field install under a name its own
    # file never mentions, and the mismatch would only surface on a machine.
    name = manifest.get("name")
    if not isinstance(name, str) or not name:
        raise StampError(
            f"{manifest_path.relative_to(root).as_posix()} has no 'name'. "
            "The manifest is the hand-written source of truth for a plugin's "
            "identity — there is nothing to derive it from."
        )
    conventions = manifest.get("conventions", [])
    if not isinstance(conventions, list) or not all(
        isinstance(c, str) for c in conventions
    ):
        raise StampError(
            f"Plugin '{plugin_dir.name}' conventions must be a list of strings, "
            f"got: {conventions!r}"
        )

    skills = tuple(
        _parse_skill(d, plugin_dir.name)
        for d in _component_dirs(plugin_dir / "skills")
    )
    agents = tuple(
        _parse_agent(d, plugin_dir.name)
        for d in _component_dirs(plugin_dir / "agents")
    )

    is_persona = plugin_dir.name.startswith("persona-")
    wants_run_hook = is_persona or plugin_dir.name.startswith("advisor-")

    sources = _hook_sources(plugin_dir, is_persona, plumbing)
    declared: list[HookWiring] = []
    summaries: dict[str, str] = {}
    for filename, source in sources.items():
        declaration = read_hook_declaration(source, filename)
        if declaration is None:
            continue  # shared library module, not a hook
        declared.append(_validate_declaration(filename, declaration))
        summaries[filename] = _parse_hook_summary(source, filename)

    hooks_json = render_hooks_json(declared) if declared else None
    hooks: list[HookDoc] = []
    if hooks_json is not None:
        emitted = _walk_hook_wiring(json.loads(hooks_json))
        for filename in sorted(summaries):
            record = emitted.get(filename, {"events": set(), "matchers": set()})
            hooks.append(
                HookDoc(
                    name=filename,
                    summary=summaries[filename],
                    plugin=plugin_dir.name,
                    events=tuple(sorted(record["events"])),
                    matchers=tuple(sorted(record["matchers"])),
                )
            )

    return PluginDoc(
        name=name,
        directory=plugin_dir,
        version=str(manifest.get("version", "0.0.0")),
        description=str(manifest.get("description", "")).strip(),
        conventions=tuple(conventions),
        manifest=manifest,
        skills=skills,
        agents=agents,
        hooks=tuple(hooks),
        hooks_json=hooks_json,
        is_persona=is_persona,
        wants_run_hook=wants_run_hook,
    )


# --------------------------------------------------------------------------- #
# The hook command string
# --------------------------------------------------------------------------- #

# One function, so re-pointing every emitted command is one edit.
#
# State of play, honestly: Claude Code sets CLAUDE_PLUGIN_ROOT to the installed
# plugin directory. Codex passes PLUGIN_ROOT instead. Cortex Code 1.20.2 sets
# NEITHER — probed, tracked as issue #634 — and the `${CLAUDE_PLUGIN_ROOT:-.}`
# form this replaces resolved that case to `.`, the *user's cwd*, which is the
# wrong directory: the hook runs, reads a tree that is not the plugin, and
# reports nothing.
#
# $WORKSHOP_PLUGIN_ROOT is the last arm: an explicit variable an operator can
# export to name the plugin root on a platform that supplies neither of the
# other two. It fails loudly (empty path) rather than silently resolving
# somewhere plausible. The Cortex arm of this expression is UNVERIFIED — nobody
# has yet run a hook on Cortex with WORKSHOP_PLUGIN_ROOT exported. It owes a
# live probe before the cutover; do not read it as known-working.
_PLUGIN_ROOT_EXPR = '"${CLAUDE_PLUGIN_ROOT:-${PLUGIN_ROOT:-$WORKSHOP_PLUGIN_ROOT}}"'


def hook_command(script: str, runner: str = "bash") -> str:
    """Return the command string that runs one hook script.

    Everything routes through ``run-hook.sh``: it derives the plugin root from
    ``${BASH_SOURCE[0]}``, so a command that invoked a hook script directly
    would have to solve the resolution problem again, per platform.
    """
    if runner not in _RUNNERS:
        raise StampError(
            f"Unknown hook runner {runner!r}; expected one of "
            f"{', '.join(sorted(_RUNNERS))}."
        )
    if runner == "vault":
        return f"bash {_PLUGIN_ROOT_EXPR}/hooks/run-vault-hook.sh {script}"
    flag = "--uv " if runner == "uv" else ""
    return f"bash {_PLUGIN_ROOT_EXPR}/hooks/run-hook.sh {flag}{script}"


# --------------------------------------------------------------------------- #
# Renderers — JSON outputs
# --------------------------------------------------------------------------- #


def _json_doc(payload: dict) -> str:
    """Serialize a generated JSON document, marker key first."""
    document = {_JSON_MARKER_KEY: GENERATED_MARKER}
    document.update(payload)
    return json.dumps(document, indent=2, ensure_ascii=False) + "\n"


def render_hooks_json(declared: list[HookWiring]) -> str:
    """Render one plugin's hooks.json from its scripts' own declarations.

    Grouped by event, scripts sorted by name, one entry per distinct matcher.
    An entry with no matcher omits the key entirely rather than emitting an
    empty string, which some platforms read as "match nothing".
    """
    by_event: dict[str, dict[str, list[HookWiring]]] = {}
    for wiring in sorted(declared, key=lambda w: w.script):
        by_event.setdefault(wiring.event, {}).setdefault(wiring.matcher, []).append(
            wiring
        )

    hooks: dict[str, list[dict]] = {}
    for event in sorted(by_event):
        entries: list[dict] = []
        # Matcher groups keep insertion order, which is the sorted-script order
        # they were built in — deterministic without a second sort key.
        for matcher, group in by_event[event].items():
            entry: dict = {}
            if matcher:
                entry["matcher"] = matcher
            entry["hooks"] = [
                {"type": "command", "command": hook_command(w.script, w.runner)}
                for w in group
            ]
            entries.append(entry)
        hooks[event] = entries
    return _json_doc({"hooks": hooks})


def render_manifest_copy(plugin: PluginDoc) -> str:
    """Render the Codex/Cortex mirror of a plugin's hand-written manifest."""
    return _json_doc(dict(plugin.manifest))


def render_conventions(plugin: PluginDoc) -> str:
    """Render a plugin's conventions.json — always the same shape, list may be empty."""
    return _json_doc({"conventions": list(plugin.conventions)})


def persona_settings_template(root: Path) -> Path:
    """Where the canonical persona `settings.json` lives, if it lives anywhere."""
    return root / "plugins" / "workbench" / "hooks" / "settings.persona.json"


def render_persona_settings(root: Path) -> str:
    """Render a persona's settings.json from the workbench template."""
    return _json_doc(_read_json(persona_settings_template(root)))


def render_marketplace(model: StampModel) -> str:
    """Render the Claude marketplace index. Sources point at the served dirs."""
    return _json_doc(
        {
            "name": MARKETPLACE_NAME,
            "owner": dict(MARKETPLACE_OWNER),
            "plugins": [
                {
                    "name": plugin.name,
                    "version": plugin.version,
                    "description": plugin.description,
                    "source": f"./plugins/{plugin.directory.name}",
                }
                for plugin in model.plugins
            ],
        }
    )


def render_codex_marketplace(model: StampModel) -> str:
    """Render the Codex marketplace index, which is a different shape.

    Codex does not read the Claude index: it wants a top-level ``interface``
    block, and each entry carries a structured ``source``, an install/auth
    ``policy``, and a ``category`` that the Claude shape has no field for.
    Emitting the Claude shape here costs nothing at stamp time and silently
    breaks discovery on one of the four surfaces the cutover has to verify —
    which is exactly the kind of failure that only shows up on a machine.
    """
    return _json_doc(
        {
            "name": MARKETPLACE_NAME,
            "interface": {"displayName": MARKETPLACE_DISPLAY_NAME},
            "plugins": [
                {
                    "name": plugin.name,
                    "source": {
                        "source": "local",
                        "path": f"./plugins/{plugin.directory.name}",
                    },
                    "policy": {
                        "installation": "AVAILABLE",
                        "authentication": "ON_INSTALL",
                    },
                    "category": "Productivity",
                }
                for plugin in model.plugins
            ],
        }
    )


# --------------------------------------------------------------------------- #
# Renderers — shared table builders
# --------------------------------------------------------------------------- #


def render_skills_table(skills: list[SkillDoc]) -> str:
    """One-line-per-skill summary table (name · plugin · summary)."""
    rows = ["| Skill | Plugin | Summary |", "| --- | --- | --- |"]
    for skill in skills:
        rows.append(
            f"| `/{skill.name}` | `{skill.plugin}` "
            f"| {_escape_cell(_first_sentence(skill.description))} |"
        )
    return "\n".join(rows)


def render_agents_table(agents: list[AgentDoc]) -> str:
    rows = ["| Agent | Plugin | Role | Skills |", "| --- | --- | --- | --- |"]
    for agent in agents:
        skills = ", ".join(f"`{s}`" for s in agent.skills_add) or "—"
        rows.append(
            f"| **{agent.name}** | `{agent.plugin}` | `{agent.role}` | {skills} |"
        )
    return "\n".join(rows)


def render_hooks_table(hooks: list[HookDoc]) -> str:
    rows = ["| Hook | Plugin | Event | Summary |", "| --- | --- | --- | --- |"]
    for hook in hooks:
        events = ", ".join(f"`{e}`" for e in hook.events) or "—"
        rows.append(
            f"| `{hook.name}` | `{hook.plugin}` | {events} "
            f"| {_escape_cell(hook.summary)} |"
        )
    return "\n".join(rows)


def render_plugins_table(plugins: list[PluginDoc]) -> str:
    """One row per plugin — there is no core/preset tier any more, just plugins."""
    rows = [
        "| Plugin | Version | Skills | Agents | Hooks | Description |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for plugin in plugins:
        rows.append(
            f"| **`{plugin.name}`** | `{plugin.version}` | {len(plugin.skills)} "
            f"| {len(plugin.agents)} | {len(plugin.hooks)} "
            f"| {_escape_cell(plugin.description)} |"
        )
    return "\n".join(rows)


def render_methodology_table(docs: list[MethodologyDoc]) -> str:
    rows = ["| Document | Plugin | Summary |", "| --- | --- | --- |"]
    for doc in docs:
        rows.append(
            f"| [`{doc.filename}`](../../plugins/{doc.plugin}/docs/{doc.filename}) "
            f"| `{doc.plugin}` | {_escape_cell(doc.summary)} |"
        )
    return "\n".join(rows)


def render_scripts_table(scripts: list[ScriptDoc]) -> str:
    rows = ["| Script | Purpose |", "| --- | --- |"]
    for script in scripts:
        rows.append(f"| `scripts/{script.filename}` | {_escape_cell(script.summary)} |")
    return "\n".join(rows)


def render_counts(model: StampModel) -> str:
    """The headline count line (single source for the README banner)."""
    return (
        f"**{len(model.skills)} skills · {len(model.agents)} agents · "
        f"{len(model.hooks)} hooks · {len(model.plugins)} plugins**"
    )


def render_platform_matrix(support: PlatformSupportDoc) -> str:
    """Compact per-platform capability table for the README."""
    header = "| Component | " + " | ".join(support.platforms) + " |"
    divider = "| --- |" + " --- |" * len(support.platforms)
    lines = [header, divider]
    for component in support.components:
        cells = " | ".join(
            component.cells[p].status.capitalize() for p in support.platforms
        )
        lines.append(f"| {_escape_cell(component.name)} | {cells} |")
    lines += [
        "",
        "Per-cell notes and evidence: "
        "[platform support reference](docs/reference/platform-support.md); "
        "how each verdict was verified: [COMPATIBILITY.md](COMPATIBILITY.md).",
    ]
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# Renderers — full catalog pages
# --------------------------------------------------------------------------- #


def _catalog_header(title: str, intro: str) -> list[str]:
    return [_MD_MARKER, "", f"# {title}", "", intro, ""]


def render_skills_page(model: StampModel) -> str:
    lines = _catalog_header(
        "Skills Reference",
        "Every skill served from `plugins/`, parsed from each skill's `SKILL.md` "
        "frontmatter. A skill ships with exactly one plugin — the one whose "
        "`skills/` directory it lives in.",
    )
    lines += ["## All skills", "", render_skills_table(model.skills), ""]
    lines += ["## Full descriptions", ""]
    for skill in model.skills:
        lines += [
            f"### `/{skill.name}`",
            "",
            f"*`{skill.plugin}` plugin*",
            "",
            skill.description,
            "",
        ]
    return "\n".join(lines).rstrip() + "\n"


def render_agents_page(model: StampModel) -> str:
    lines = _catalog_header(
        "Agents Reference",
        "Specialized subagent roles, parsed from each agent's `AGENT.md` "
        "frontmatter. An agent ships with the plugin whose `agents/` directory "
        "it lives in.",
    )
    lines += ["## All agents", "", render_agents_table(model.agents), ""]
    lines += ["## Details", ""]
    for agent in model.agents:
        skills = ", ".join(f"`{s}`" for s in agent.skills_add) or "none"
        lines += [
            f"### {agent.name}",
            "",
            f"*`{agent.plugin}` plugin · role `{agent.role}` · skills: {skills}*",
            "",
            agent.description,
            "",
        ]
    return "\n".join(lines).rstrip() + "\n"


def render_hooks_page(model: StampModel) -> str:
    lines = _catalog_header(
        "Hooks Reference",
        "Lifecycle hooks and the events they run on. The event column is read "
        "back out of each plugin's generated `hooks/hooks.json` — the file that "
        "actually ships — and the summary is the hook module's docstring. See "
        "[platform-support.md](platform-support.md) for the per-platform truth "
        "table.",
    )
    lines += ["## All hooks", "", render_hooks_table(model.hooks), ""]
    lines += ["## Details", ""]
    for hook in model.hooks:
        events = ", ".join(f"`{e}`" for e in hook.events) or "not currently wired"
        matchers = ", ".join(f"`{m}`" for m in hook.matchers) or "—"
        lines += [
            f"### `{hook.name}`",
            "",
            f"*`{hook.plugin}` plugin · events: {events} · matcher: {matchers}*",
            "",
            hook.summary,
            "",
        ]
    return "\n".join(lines).rstrip() + "\n"


def render_plugins_page(model: StampModel) -> str:
    lines = _catalog_header(
        "Plugins Reference",
        "Every plugin the marketplace serves, with the skills, agents, hooks, "
        "and conventions each one ships. The directories under `plugins/` are "
        "served in place — there is no build step and no `dist/`.",
    )
    lines += ["## All plugins", "", render_plugins_table(model.plugins), ""]
    lines += ["## Details", ""]
    for plugin in model.plugins:
        lines += [
            f"### `{plugin.name}`",
            "",
            f"*v{plugin.version} · `plugins/{plugin.directory.name}`*",
            "",
            plugin.description or "_no description_",
            "",
        ]
        if plugin.conventions:
            lines += ["**Conventions:**", ""]
            lines += [f"- {c}" for c in plugin.conventions]
            lines += [""]
        if plugin.skills:
            lines += [
                f"**Skills ({len(plugin.skills)}):** "
                + ", ".join(f"`{s.name}`" for s in plugin.skills),
                "",
            ]
        if plugin.agents:
            lines += [
                f"**Agents ({len(plugin.agents)}):** "
                + ", ".join(f"`{a.name}`" for a in plugin.agents),
                "",
            ]
        if plugin.hooks:
            lines += [
                f"**Hooks ({len(plugin.hooks)}):** "
                + ", ".join(f"`{h.name}`" for h in plugin.hooks),
                "",
            ]
    return "\n".join(lines).rstrip() + "\n"


def render_methodology_page(model: StampModel) -> str:
    lines = _catalog_header(
        "Methodology Reference",
        "The working-method docs a plugin ships under its own `docs/`. Each is "
        "summarized from its source file in the plugin that owns it.",
    )
    lines += [render_methodology_table(model.methodology), ""]
    for doc in model.methodology:
        lines += [f"## {doc.title}", "", doc.summary, ""]
    return "\n".join(lines).rstrip() + "\n"


def render_platform_support_page(model: StampModel) -> str:
    support = model.platform_support
    lines = _catalog_header(
        "Platform Support Reference",
        "What each component class actually does on each target platform, "
        "rendered from `scripts/platform-support.json`. Every verdict is "
        "grounded in a section of [COMPATIBILITY.md](../../COMPATIBILITY.md), "
        "which records how it was verified — a claim without recorded evidence "
        "is marked `unverified`, not assumed to work.",
    )
    lines += [render_platform_matrix(support), ""]
    for component in support.components:
        lines += [f"## {component.name}", ""]
        for platform in support.platforms:
            cell = component.cells[platform]
            note = f" — {cell.note}" if cell.note else ""
            compat = f" _(COMPATIBILITY.md → {cell.compat})_" if cell.compat else ""
            lines.append(f"- **{platform}: {cell.status}**{note}{compat}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_plugin_readme(plugin: PluginDoc) -> str:
    """Render a plugin's shipped README from its manifest and its components."""
    lines = [
        _MD_MARKER,
        "",
        f"# {plugin.name}",
        "",
        plugin.description or "_no description_",
        "",
    ]
    if plugin.conventions:
        lines += ["## Conventions", ""]
        lines += [f"- {c}" for c in plugin.conventions]
        lines += [""]
    if plugin.skills:
        lines += ["## Skills", ""]
        lines += ["| Skill | Summary |", "| --- | --- |"]
        for skill in sorted(plugin.skills, key=lambda s: s.name):
            lines.append(
                f"| `/{_escape_cell(skill.name)}` "
                f"| {_escape_cell(_first_sentence(skill.description))} |"
            )
        lines.append("")
    if plugin.agents:
        lines += ["## Agents", ""]
        lines += ["| Agent | Role | Summary |", "| --- | --- | --- |"]
        for agent in sorted(plugin.agents, key=lambda a: a.name):
            lines.append(
                f"| {_escape_cell(agent.name)} | `{_escape_cell(agent.role)}` "
                f"| {_escape_cell(_first_sentence(agent.description))} |"
            )
        lines.append("")
    if plugin.hooks:
        lines += ["## Hooks", ""]
        lines += ["| Hook | Event | Summary |", "| --- | --- | --- |"]
        for hook in sorted(plugin.hooks, key=lambda h: h.name):
            events = ", ".join(f"`{e}`" for e in hook.events) or "—"
            lines.append(
                f"| `{_escape_cell(hook.name)}` | {events} "
                f"| {_escape_cell(hook.summary)} |"
            )
        lines.append("")
    lines += [
        "## Install",
        "",
        "```",
        "/plugin marketplace add cdcoonce/the-workshop",
        f"/plugin install {plugin.name}@{MARKETPLACE_NAME}",
        "```",
        "",
    ]
    return "\n".join(lines).rstrip() + "\n"


# --------------------------------------------------------------------------- #
# Marker rewriting
# --------------------------------------------------------------------------- #


_BEGIN_ANY_RE = re.compile(r"<!-- BEGIN GENERATED: ([A-Za-z0-9_-]+) -->")
_END_ANY_RE = re.compile(r"<!-- END GENERATED: ([A-Za-z0-9_-]+) -->")


def rewrite_markers(text: str, blocks: dict[str, str]) -> str:
    """Replace the content inside each GENERATED marker with blocks[id].

    A marker id present in the text with no registered block is an error (a stale
    marker). Registered blocks with no marker in this file are fine — a file uses
    whatever subset of ids it declares. Idempotent: the replacement content is
    stored without a trailing newline and wrapped identically each run.

    Two integrity guards, since these markers gate the whole doc pipeline:
    a block whose content contains its own END marker literal would truncate its
    own region on the next run (unbounded growth), and a half-deleted or
    id-mismatched marker pair would silently be skipped. Both raise StampError.
    """
    seen: set[str] = set()

    def _replace(match: re.Match) -> str:
        marker_id = match.group("id")
        seen.add(marker_id)
        if marker_id not in blocks:
            raise StampError(
                f"GENERATED marker '{marker_id}' has no registered content; "
                "remove the marker or add a block for it in scripts/stamp.py."
            )
        body = blocks[marker_id].strip("\n")
        if f"<!-- END GENERATED: {marker_id} -->" in body:
            raise StampError(
                f"Generated block '{marker_id}' contains its own END marker "
                "literal; block content cannot include the marker syntax."
            )
        return (
            f"<!-- BEGIN GENERATED: {marker_id} -->\n"
            f"{body}\n"
            f"<!-- END GENERATED: {marker_id} -->"
        )

    result = _MARKER_RE.sub(_replace, text)

    # Any BEGIN/END marker left in the text that wasn't part of a matched pair is
    # orphaned or id-mismatched (e.g. a deleted END, or BEGIN `x` / END `y`).
    orphaned = (
        set(_BEGIN_ANY_RE.findall(result)) | set(_END_ANY_RE.findall(result))
    ) - seen
    if orphaned:
        raise StampError(
            "Unpaired or id-mismatched GENERATED marker(s): "
            f"{', '.join(sorted(orphaned))}. Each needs a matching BEGIN/END pair "
            "with an identical id."
        )
    return result


def readme_blocks(model: StampModel) -> dict[str, str]:
    """GENERATED marker blocks for the root README.

    There is no core-vs-preset tier any more, so the split tables it needed
    (`skills-table` + `preset-skills-table`, `agents-core-table` +
    `agents-preset-table`) collapse to one each.
    """
    blocks = {
        "counts": render_counts(model),
        "skills-table": render_skills_table(model.skills),
        "agents-table": render_agents_table(model.agents),
        "hooks-table": render_hooks_table(model.hooks),
        "plugins-table": render_plugins_table(model.plugins),
        "methodology-table": render_methodology_table(model.methodology),
    }
    if model.platform_support is not None:
        blocks["platform-matrix"] = render_platform_matrix(model.platform_support)
    return blocks


def wiring_blocks(model: StampModel) -> dict[str, str]:
    """GENERATED marker blocks for docs/reference/build-and-wiring.md."""
    return {
        "scripts-table": render_scripts_table(model.scripts),
        "hooks-wiring-table": render_hooks_table(model.hooks),
    }


# --------------------------------------------------------------------------- #
# The path map
# --------------------------------------------------------------------------- #


def _render(root: Path) -> tuple[dict[Path, str], set[Path]]:
    """Render every owned path in memory.

    Returns ``(outputs, hand_owned)``. ``hand_owned`` is the subset whose file is
    human-owned and only has GENERATED marker *regions* rewritten — those carry
    no whole-file marker, so the overwrite refusal cannot apply to them.
    """
    model = build_model(root)
    outputs: dict[Path, str] = {}
    hand_owned: set[Path] = set()

    for plugin in model.plugins:
        directory = plugin.directory
        manifest_copy = render_manifest_copy(plugin)
        outputs[directory / ".codex-plugin" / "plugin.json"] = manifest_copy
        outputs[directory / ".cortex-plugin" / "plugin.json"] = manifest_copy
        outputs[directory / "README.md"] = render_plugin_readme(plugin)
        outputs[directory / "conventions.json"] = render_conventions(plugin)
        if plugin.hooks_json is not None:
            outputs[directory / "hooks" / "hooks.json"] = plugin.hooks_json
        if plugin.is_persona:
            injector = model.persona_plumbing.get("inject_persona.py")
            if injector is not None:
                outputs[directory / "hooks" / "scripts" / "inject_persona.py"] = injector
            # Only stamp a settings.json when there is a canonical one to copy.
            # Emitting a file whose entire content is "I was generated" tells a
            # reader nothing and invites someone to put real settings in the
            # copy rather than in the template every persona shares.
            if persona_settings_template(root).exists():
                outputs[directory / "settings.json"] = render_persona_settings(root)
        if plugin.wants_run_hook:
            runner = model.persona_plumbing.get("run-hook.sh")
            if runner is not None:
                outputs[directory / "hooks" / "run-hook.sh"] = runner

    outputs[root / ".claude-plugin" / "marketplace.json"] = render_marketplace(model)
    outputs[root / ".agents" / "plugins" / "marketplace.json"] = render_codex_marketplace(model)

    reference = root / "docs" / "reference"
    outputs[reference / "skills.md"] = render_skills_page(model)
    outputs[reference / "agents.md"] = render_agents_page(model)
    outputs[reference / "hooks.md"] = render_hooks_page(model)
    outputs[reference / "plugins.md"] = render_plugins_page(model)
    outputs[reference / "methodology.md"] = render_methodology_page(model)
    if model.platform_support is not None:
        outputs[reference / "platform-support.md"] = render_platform_support_page(model)

    readme_path = root / "README.md"
    if readme_path.exists():
        outputs[readme_path] = rewrite_markers(
            readme_path.read_text(encoding="utf-8"), readme_blocks(model)
        )
        hand_owned.add(readme_path)

    wiring_path = reference / "build-and-wiring.md"
    if wiring_path.exists():
        outputs[wiring_path] = rewrite_markers(
            wiring_path.read_text(encoding="utf-8"), wiring_blocks(model)
        )
        hand_owned.add(wiring_path)

    return outputs, hand_owned


def owned_paths(root: Path) -> dict[Path, str]:
    """Return {absolute path: exact desired content} for every file the stamper owns.

    Pure: renders in memory and writes nothing. The twelve owned path classes are

    1. ``plugins/<n>/.codex-plugin/plugin.json``
    2. ``plugins/<n>/.cortex-plugin/plugin.json``
    3. ``plugins/<n>/README.md``
    4. ``plugins/<n>/conventions.json``
    5. ``plugins/<n>/hooks/hooks.json`` (only where the plugin ships hook scripts)
    6. ``plugins/persona-*/hooks/scripts/inject_persona.py``
    7. ``plugins/{persona,advisor}-*/hooks/run-hook.sh``
    8. ``plugins/persona-*/settings.json``
    9. ``.claude-plugin/marketplace.json``
    10. ``.agents/plugins/marketplace.json``
    11. ``docs/reference/{skills,hooks,agents,plugins,methodology,platform-support}.md``
    12. the GENERATED marker regions of ``README.md`` and
        ``docs/reference/build-and-wiring.md``

    ``plugins/<n>/.claude-plugin/plugin.json`` is never owned: it is the
    hand-written source, and a stamper that both read and wrote it could rewrite
    the only declaration of a plugin's version from a bad render.
    """
    return _render(root)[0]


# --------------------------------------------------------------------------- #
# Write / check
# --------------------------------------------------------------------------- #


def _guard_overwrite(root: Path, path: Path) -> None:
    """Refuse to write over a file that carries no generation marker."""
    if not path.exists():
        return
    text = path.read_text(encoding="utf-8", errors="replace")
    if GENERATED_MARKER in text:
        return
    if any(marker in text for marker in _PREDECESSOR_MARKERS):
        return
    relative = path.relative_to(root).as_posix()
    if relative in _CUTOVER_ADOPTED:
        return
    raise StampError(
        f"Refusing to overwrite '{relative}': it exists and carries no "
        f"'{GENERATED_MARKER}' marker, so it is hand-written work rather than "
        "stamper output. Move it aside, or fix the path map that claims it."
    )


def stamp(root: Path) -> list[Path]:
    """Write every owned path; return the sorted list of paths written.

    Every refusal is checked before any write, so a run that refuses leaves the
    tree exactly as it found it.
    """
    outputs, hand_owned = _render(root)
    for path in sorted(outputs):
        if path in hand_owned:
            continue
        _guard_overwrite(root, path)
    for path in sorted(outputs):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(outputs[path], encoding="utf-8")
    return sorted(outputs)


def check(root: Path) -> list[tuple[Path, str]]:
    """Return (path, unified diff) for every owned path that has drifted."""
    outputs, _ = _render(root)
    drifted: list[tuple[Path, str]] = []
    for path in sorted(outputs):
        desired = outputs[path]
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current == desired:
            continue
        relative = path.relative_to(root).as_posix()
        diff = "".join(
            difflib.unified_diff(
                current.splitlines(keepends=True),
                desired.splitlines(keepends=True),
                fromfile=f"{relative} (on disk)",
                tofile=f"{relative} (stamped)",
            )
        )
        drifted.append((path, diff))
    return drifted


def main(argv: list[str] | None = None, *, root: Path | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="scripts.stamp",
        description="Stamp the repo's generated files from the flat plugin tree.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Report drift and exit non-zero without writing anything.",
    )
    args = parser.parse_args(list(sys.argv[1:] if argv is None else argv))
    root = Path.cwd() if root is None else root

    if args.check:
        drifted = check(root)
        if not drifted:
            print("Stamped output is up to date.")
            return 0
        print(
            "Stamped output is stale — run `make stamp` and commit:", file=sys.stderr
        )
        for path, _ in drifted:
            print(f"  - {path.relative_to(root).as_posix()}", file=sys.stderr)
        for _, diff in drifted:
            if diff:
                print(diff, file=sys.stderr, end="")
        return 1

    written = stamp(root)
    print(f"Stamped {len(written)} file(s):")
    for path in written:
        print(f"  - {path.relative_to(root).as_posix()}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except StampError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc
